### ISSUE TITLE
nvm use down not work while user home directory have space

### ISSUE THREAD

**Issue by liyangdal** [coreybutler/nvm-windows#161] opened 2016-04-10 06:50 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

None of above

### Expected Behavior

My home directory is something like C:\Users\xxx yyy\ which have a space between xxx and yyy

Step 1. Installing via installer.
Step 2. nvm install 4.4.2
Step 3. nvm use 4.4.2

### Actual Behavior

in Step 3, I got error message like
exit status 1: 'C:\Users\xxx' is not recognized as an internal or external command, operable program or batch file.

### Steps to reproduce the problem:

install and use nvm by a user which home directory have a space.

**Comment by micha-LEAP** [comment] 2016-04-13 03:22
I watched the disk usage during an `nvm install` process. It seems the node executable is downloaded directly to the version folder under AppDate\Roaming\nvm, but the npm insallation downloads to AppData\Roaming\nvm\temp\npm which should then be moved to the version folder.

So I tried  `nvm install 4.4.2` and watched it, and saw the move process write the npm folder to v4.4.2\node_modules - success!

I then tried uninstalling v4.3.0 and manually removed the version folder as instructed. Then proceeded to reinstall the version with `nvm install 4.3.0` and this time the npm folder was moved successfully! Since then, each other version installation has worked properly. Perhaps it is just the very first version install that is failing?

**Comment by alexbooker** [comment] 2016-04-15 08:37
I have the same problem :cry:

**Comment by alexbooker** [comment] 2016-04-15 08:53
Here's the solution:

1. Uninstall nvm via the Control Panel
2. Install nvm via nvm-setup.exe
3. When prompted, change the install path from _C:\Users\<Username with space>\AppData\Roaming\nvm_ install to _C:\Users\Public\nvm_.

Running `nvm root` should now show _C:\Users\Public\nvm_ and things **should** just work.

**Comment by Ugarz** [comment] 2016-04-16 14:07
Hi there !
Same issue here but I could not fix it. I'm using the casual prompt, and installed cygwin mod.
1. I uninstalled nvm and node.
2. Install node (in `64bits` with the `.msi`).
3. Install nvm for windows replacing my spaced name with `Public` in the install path.
4. After my test here what it prompt :
![node](https://cloud.githubusercontent.com/assets/6050079/14581402/bed401c0-03ec-11e6-9159-a9fde9e4d5b5.JPG)

**Comment by semi-xi** [comment] 2016-04-23 07:51
the same problem as Ugarz 
and when i uninstall all the node before i install the nvm-windows .after that open cmd.ext . it tell me that "erroe open setting.txt :  the system canot find the file specified “

**Comment by coreybutler** [comment] 2016-06-04 20:35
Duplicate of #41.

**Closed by coreybutler** 2016-06-04 20:35 UTC

**Comment by fullsteack** [comment] 2020-01-21 14:54
1. In cmd, go to your home directory and type dir/x to see the shortened name for this folder
2. Then replace your user name with this shortened name in the setting.txt
3. It works

**Comment by MdRasheedAhmed** [comment] 2020-07-21 14:31
> 1. In cmd, go to your home directory and type dir/x to see the shortened name for this folder
> 2. Then replace your user name with this shortened name in the setting.txt
> 3. It works

This Works..Thanks

**Comment by meenakshi777** [comment] 2020-07-21 14:34
It works for me..! Thanks

**Comment by arahmanmdmajid** [comment] 2021-02-22 19:28
> 1. In cmd, go to your home directory and type dir/x to see the shortened name for this folder
> 2. Then replace your user name with this shortened name in the setting.txt
> 3. It works

Work for me too, Thanks
