### ISSUE TITLE
Allow specification of only the major or minor release number.

### ISSUE THREAD

**Issue by jamestalmage** [coreybutler/nvm-windows#172] opened 2016-05-26 21:26 UTC
### My Environment

- [x] Windows 7 or below (not truly supported due to EOL)
- [x] Windows Server 2012 R2

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Description:

Currently, you are required to specify the full version of the Node release you want. This makes it impractical for CI server environments, where we just want to run the latest versions of the Node releases we support:

```sh
# Only major version is specified. Install latest version that matches 5.x.x
nvm install 5
# Major and minor version specified. Install latest version that matches 0.12.x
nvm install 0.12
```

**Comment by coreybutler** [comment] 2016-05-26 21:28
Duplicate of #156.

**Closed by coreybutler** 2016-05-26 21:28 UTC
Labels: duplicate

**Comment by jamestalmage** [comment] 2016-05-26 21:30
Argh! I searched for it. Sorry.

**Comment by coreybutler** [comment] 2016-05-27 16:26
@jamestalmage No worries!
