### ISSUE TITLE
nvm use [major] doesn't work properly

### ISSUE THREAD

**Issue by joseph-parsley** [coreybutler/nvm-windows#839] opened 2022-07-26 20:10 UTC
**Issue: `nvm use [major]` doesn't work properly**
If you attempt to try something like `nvm use 14` when you have a node v14.x.x installed, you get an error message. 

**How To Reproduce:**

1. Have a major version of node (example `14.17.3`) installed
2. `npm use 14`
3. Receive error message

**Expected Behavior:**

The latest version of node v14 should be used.

**Additional context:**
It seems possible this could be a typo on a feature that should work because it looks like it's very close to working:
```
$ nvm use 14
node vv14.17.3 (64-bit) is not installed or cannot be found.
```
The extra `v` makes it look like it's trying to do the correct thing behind the scenes but the extra character makes it not work.
This functionality works as I'd expect it to if I do `nvm install 14`, it installs the latest version of that major version.

**Comment by coreybutler** [comment] 2022-07-27 16:27
Duplicate of #708.

**Closed by coreybutler** 2022-07-27 16:27 UTC
Labels: duplicate
