### ISSUE TITLE
Issue:When I use nvm root somepath to change the root,nvm use didn't work,it can't find the elevate.cmd file

### ISSUE THREAD

**Issue by chenzanlee** [coreybutler/nvm-windows#352] opened 2018-05-12 13:18 UTC
Hi,After I use nvm root to modify the root path to store the nodejs files that I download,I run into this problem——I can use nvm install command to download the nodejs to the new root directory,but I can't use the nvm use command.When I use nvm use,I just get this message:"mynewrootpath/elevate.cmd": file doesn't exist. I fix this by copy the two file in my installation path to the new root path,What I get from the nvm help infomation is that this command just changes the path for store nodejs files,I wonder why I need manually copy the two file,should it just auto copy this two file to the new root directory if it need this two file in the new root path so that it can work correctly.by the way, I use the uninstaller version.I'm curious is there anyone else has encounter the same problem?
![_20180512211817](https://user-images.githubusercontent.com/16750457/39957708-066ecccc-562a-11e8-8157-a7bab94dca90.png)

### My Environment Windows 10
 My Windows installation is non-English.

**Comment by lordscales91** [comment] 2019-06-17 13:43
I guess that probably this is the root cause:

https://github.com/coreybutler/nvm-windows/blob/51de9564a2292c4aee5e15432d7f6d44db3e48e0/src/nvm.go#L663-L664

I think the second line is creating a wrong sym link to elevate.vbs 
But this just a wild guess though, I've never seen any Go code before, but this looks like the classical copy-paste typo.

**Comment by santanuchakrabarti** [comment] 2019-12-26 14:24
I faced the same issue with the latest release of NVM4W. I couldn't find any solution for this and so went for the same work around as mentioned above. I copied the files elevate.cmd and elevate.vbs from the installation directory to the nodejs root directory.

**Comment by coreybutler** [comment] 2019-12-27 15:08
@chenzanlee You definitely need to upgrade. There are a number of issues resolved in 1.1.7, including a change to support npm's hard coded changes.

@santanuchakrabarti - that does look like a copy/paste error. I've fixed it in https://github.com/coreybutler/nvm-windows/commit/88353cfcea140e02e2b13584fd89454adc9f52b3, though I'm not convinced it will resolve the issue in all situations. It should work in most situations, but there could be edge cases related to permissions.

**Comment by coreybutler** [comment] 2021-12-16 02:31
Closing due to age. Several new releases have been published since this issue was filed.

**Closed by coreybutler** 2021-12-16 02:31 UTC
