### ISSUE TITLE
set 'proxy' with incorrect parameter make nvm always crash

### ISSUE THREAD

**Issue by Himself65** [coreybutler/nvm-windows#507] opened 2020-02-09 10:16 UTC
### My Environment

- [X] Windows 10

### I'm using NVM4W version: 

Run `nvm version` if you don't know.

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [X] settings.txt
- [X] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Actual Behavior

```bash
C:\Users\Himself65>nvm version
1.1.7

C:\Users\Himself65>nvm proxy .

C:\Users\Himself65>nvm
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.Setup()
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:685 +0x8ed
main.main()
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:60 +0x61
```

I think you didn't check if it's the valid parameter when setting.

**Comment by Himself65** [comment] 2020-02-09 10:23
related code:

https://github.com/coreybutler/nvm-windows/blob/88353cfcea140e02e2b13584fd89454adc9f52b3/src/nvm.go#L728-L751

**Comment by randomactions** [comment] 2020-08-03 17:14
Hi, just passing by and wanted to check if this PR is going to be merged, as as of v1.1.7 the issue is still present

**Comment by randomactions** [comment] 2020-08-03 17:17
And also, since `nvm off` is not working now, how do I uninstall it?

**Comment by Himself65** [comment] 2020-08-03 17:19
> Hi, just passing by and wanted to check if this PR is going to be merged, as as of v1.1.7 the issue is still present

I think no, this project has no longer maintained

**Comment by coreybutler** [comment] 2020-08-03 21:36
@randomactions the project is still maintained, but I don't have a Windows machine to test on at the moment.

**Comment by sher04lock** [comment] 2021-03-11 14:47
Hi, is there any workaround for current version to have nvm working again?

**Comment by coreybutler** [comment] 2021-03-11 14:54
The issue here is `.` is not a valid proxy. A proxy needs to be a URL. If you're receiving this error, manually reset the proxy in the `settings.txt` file (in the local nvm4w installation root).

**Comment by sher04lock** [comment] 2021-03-11 14:55
Hi, for anyone who's trying to get back `nvm` working again, removing line with `proxy` in `settings.txt` worked for me:
```diff
root: C:\Users\USER\AppData\Roaming\nvm
arch: 64
- proxy: -h
originalpath: 
originalversion: 
node_mirror: 
npm_mirror: 
```
nvm version: 1.1.5

**Closed** 2021-09-11 05:36 UTC

**Comment by tekeroth-snapcode** [comment] 2022-11-28 15:25
I just installed nvm-windows, and my settings.txt looks like this:

```
root: C:\Users\wagge\AppData\Roaming\nvm
path: C:\Program Files\nodejs
```
No "proxy" in there, but I get the same error.

![image](https://user-images.githubusercontent.com/104069264/204315556-aca2510b-b07b-4eb2-b1a8-2e79c4998228.png)

Is this projet maintained?

**Comment by ehabx2007** [comment] 2022-11-29 04:19
> I just installed nvm-windows, and my settings.txt looks like this:
> 
> ```
> root: C:\Users\wagge\AppData\Roaming\nvm
> path: C:\Program Files\nodejs
> ```
> 
> No "proxy" in there, but I get the same error.
> 
> ![image](https://user-images.githubusercontent.com/104069264/204315556-aca2510b-b07b-4eb2-b1a8-2e79c4998228.png)
> 
> Is this projet maintained?

same issue with me, no proxy in settings

![image](https://user-images.githubusercontent.com/6366176/204437930-ffd3db68-b205-4960-aca6-0ac96afabcf9.png)

**Comment by SashoStzPakAz** [comment] 2022-12-05 18:51
I have the same problem, cannot install nodejs ...

**Comment by bozzgo13** [comment] 2022-12-08 15:56
same problem here.
![image](https://user-images.githubusercontent.com/17859676/206494983-4bd39524-0d1c-4473-8c72-3b1b475aa43e.png)
Nothing special in settings.txt
![image](https://user-images.githubusercontent.com/17859676/206495597-64df262c-0462-43c6-98b4-2939abbed615.png)

**Comment by c33s** [comment] 2022-12-08 17:08
@bozzgo13 try `nvm install 16.18.1` (without the `version` part)

**Comment by bozzgo13** [comment] 2022-12-08 20:43
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)

this helped me. Tnx a lot

**Comment by nvenhuizen14** [comment] 2022-12-13 15:15
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)
thaaannnnkkk youuuuu jesus lol

**Comment by ceponatia** [comment] 2022-12-14 17:55
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)

You can also use 'nvm install latest' if you want to install the latest version of Node.

What I don't understand is why the panic appears to be looking for files on the developers OneDrive. Is there a way to edit this?

**Comment by huntg** [comment] 2023-02-15 21:02
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)

Oh wow! Thanks

**Comment by MotoMatt5040** [comment] 2023-02-23 18:11
For those of you having trouble, do as follows (WINDOWS 10)

>nvm install latest

go to file explorer and browse to %AppData%, make sure you're in the Roaming folder

Find the folder titles v##.#.# (in my case v19.7.0)

back into cmd/powershell/whatever

>nvm use 19.7.0

do not include the v

>node -v

Verify your node version.

**Comment by ramakrisha** [comment] 2023-02-28 05:04
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)

Thank you. Its worked for me

**Comment by luizamarlene** [comment] 2023-04-05 21:39
> @bozzgo13 try `nvm install 16.18.1` (without the `version` part)

Thank you!!!!

**Comment by liudonghua123** [comment] 2023-04-19 01:16
I have the same problem, I did not set proxy.

```
C:\Users\Liu.D.H>nvm install 20.0.0
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x118160c8, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x118160c8, 0x6}, {0x6e9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

C:\Users\Liu.D.H>nvm version
1.1.10

C:\Users\Liu.D.H>node -v
v18.14.2

C:\Users\Liu.D.H>
C:\Users\Liu.D.H>where nvm
C:\Users\Liu.D.H\AppData\Roaming\nvm\nvm.exe

C:\Users\Liu.D.H>cat C:\Users\Liu.D.H\AppData\Roaming\nvm\settings.txt
root: C:\Users\Liu.D.H\AppData\Roaming\nvm
path: C:\Program Files\nodejs

C:\Users\Liu.D.H>
```

**Comment by liudonghua123** [comment] 2023-04-19 01:20
After I update nvm to 1.1.11, it seems works again.

**Comment by iamxyntho** [comment] 2023-06-18 23:36
Same with me here, after updating nvm to v1.1.11, this works.
