### ISSUE TITLE
nvm use fails to detect latest minor version when executed with major version only

### ISSUE THREAD

**Issue by drory82** [coreybutler/nvm-windows#770] opened 2022-03-08 08:40 UTC
Run: 
```
nvm use 8
```

Fails with:
```
node vv8.17.0 (64-bit) is not installed or cannot be found.
```

Note the "double v" in the reported version.
It seems that it finds the suitable version, but add an extra 'v' to the version which fail it to use it properly.

Probably this is the culprit:
https://github.com/coreybutler/nvm-windows/blob/5803c4f8c7766c670996fbce3fc113a9b0d95050/src/node/node.go#L47
It should replace the leading 'v' in the version argument before checking the file existence which already adding a leading 'v' to the file path. (or similar fix)

**Comment by coreybutler** [comment] 2022-03-08 14:21
Closing as a duplicate of #708.

**Closed by coreybutler** 2022-03-08 14:21 UTC
Labels: duplicate
