### ISSUE TITLE
Throws ERROR open \settings.txt in windows 7 

### ISSUE THREAD

**Issue by byteshiva** [coreybutler/nvm-windows#39] opened 2015-02-10 17:38 UTC
I'm getting this error "ERROR open \settings.txt: The system cannot find the file specified." after installing in windows 7.

![image](https://cloud.githubusercontent.com/assets/10637299/6132626/bc4998dc-b179-11e4-80d5-c634d8bf8b48.png)

**Comment by coreybutler** [comment] 2015-02-10 17:40
Closing as a duplicate of issue #15.

**Closed by coreybutler** 2015-02-10 17:40 UTC
Labels: duplicate

**Comment by byteshiva** [comment] 2015-02-10 17:48
I'm getting the same error after installing 1.6.0 with hotfix.


![image](https://cloud.githubusercontent.com/assets/10637299/6132788/13ebb3da-b17b-11e4-8d10-fc1ed2511c1e.png)

PFA for settings.txt folder

![image](https://cloud.githubusercontent.com/assets/10637299/6132799/2cb09eda-b17b-11e4-8fad-3afd4636a271.png)

**Comment by coreybutler** [comment] 2015-02-10 17:51
Sorry, I referenced the wrong issue when I closed this. It has still been filed before though. Please see issue #22.

**Comment by byteshiva** [comment] 2015-02-10 18:08
The workaround mentioned in #22 worked!!

For wider audience I'm detailing the steps
Steps followed, 
1. Open cmd using Admin Privilege
2. cd c:\users\<username>\AppData\Roaming\nvm
3. cp settings.txt to c:\

![image](https://cloud.githubusercontent.com/assets/10637299/6133141/f1703da0-b17d-11e4-9a3b-4cb1612324ae.png)

I could use to copy settings.txt to c:\ .

**Comment by reflexdemon** [comment] 2015-09-21 10:51
Oops! none of the workaround works for me.

I get the below error.

```
cp: cannot create regular file 'c:\\settings.txt': Permission denied
```

**Comment by jamesmanning** [comment] 2015-11-02 01:56
@reflexdemon needs to be an elevated cmd - make sure the title bar of the cmd.exe window says "Administrator:" like in the sshot.

**Comment by reflexdemon** [comment] 2015-11-03 11:53
@jamesmanning apparently, I have a to do this on my work machine where I dont have admin rights.

**Comment by dreamingUpCode** [comment] 2015-11-16 12:33
Had the same issue on Win 10. Reinstalled it and works fine now.

**Comment by jamiehutber** [comment] 2015-11-24 14:30
I know its stupid, but I don't really like having a settings file in my root :( I like a clean drive at all times

**Comment by jamesmanning** [comment] 2015-11-24 15:57
@jamiehutber @reflexdemon just [searching for settings.txt](https://github.com/coreybutler/nvm-windows/search?utf8=%E2%9C%93&q=settings.txt) seems to indicate that it's looking for the file related to the NVM_HOME environment variable, so setting that might be sufficient?

From an elevated cmd prompt, you should be able to run:

    setx /m NVM_HOME %APPDATA%\nvm  

Then open a new cmd prompt (so it has that variable set, it won't populate into existing ones) and try nvm without settings.txt in the root?

Seems like the install mechanism should set that variable if it's not already set, I would guess?  

It looks like [the 'manual' install method already does so](https://github.com/coreybutler/nvm-windows/blob/a0ce187f6e21f9c8a69f0f65c5c54668c016b42f/bin/install.cmd#L3), AFAICT.

**Comment by lorezzed** [comment] 2016-01-07 08:03
@byteshiva use "copy" instead of "cp" if you don't have cygwin:
`copy settings.txt c:\`

Works a treat thanks.

**Comment by kpentchev** [comment] 2016-01-16 11:19
@jamesmanning thank you!

**Comment by henrycaosg** [comment] 2016-04-09 03:48
@jamesmanning thank you!

**Comment by kkoci** [comment] 2016-05-07 17:44
@byteshiva Awesome, worked like a charm!

**Comment by fritx** [comment] 2016-05-17 08:43
When I clicked the `install.cmd`, the settings.txt prompted, but I didn't save the file.
The settings.txt would never prompt again.
What could I do?

**Comment by errorx666** [comment] 2016-06-09 15:11
@jamesmanning Works great.

Now why doesn't the installer do this for you?

**Comment by coreybutler** [comment] 2016-06-09 17:29
@errorx666 - The installer attempts to do this. However; I've seen hundreds of configurations now that are pretty customized... typically the installer fails silently due to a missing permission. The next version will have a new installer, but that may still be a ways off. Installers are, without any doubt whatsoever, the most time consuming element of this entire project. 

For anyone coming across this, I'm looking for contributors who will build and maintain installers across different operating systems.

**Comment by errorx666** [comment] 2016-06-09 17:37
@coreybutler It may be as easy as changing the installer filename.  IIRC, Windows uses the `setup.exe` filename as a heuristic for backwards compatibility, and automatically creates a UAC prompt to elevate to admin privileges.  I'm not sure if Windows' default configuration of opening zip files as "Compressed Folders" affects anything, but in my case, it removed the "Run as Administrator" option from the context menu, and probably led to my broken installation.
