### ISSUE TITLE
nvm with node 8.12.0 won't install npm 6.4.1

### ISSUE THREAD

**Issue by kb-coder** [coreybutler/nvm-windows#393] opened 2018-09-17 19:25 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.7
- [ X] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ X] read the README to be aware of npm gotchas & antivirus issues.
- [ X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ X] verified I'm using an account with administrative privileges.
- [ X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Actual Behavior

From nvm, I installed node 8.12.0. I expected it to install npm 6.4.1 with it, but I received an error message about pulling the latest version of npm from http://github.com/npm/npm/releases/tag/v[version number]. I found and installed the 6.4.1 version of npm last week at this URL: **https://github.com/npm/cli/releases/tag/v6.4.1**. This morning, when I switched to an older version of node, the new version can no longer find npm.

nvm use 6.10.0
did stuff
nvm use 8.12.0
npm run build

Received an error saying 'npm' is not recognized.

### Steps to reproduce the problem:

1. Install node 8.12.0 (nvm install 8.12.0)
2. npm 6.4.1 is not installed. Work around by installing npm 6.4.1 from https://github.com/npm/cli/releases/tag/v6.4.1.
3. run a command and verify npm works.
4. change version of node to older version.
5. Change it back to 8.12.0
6. Run npm command. (here's where it can't find npm).

**Comment by B3zo0** [comment] 2018-09-17 19:33
Duplicate of #373
You should update nvm4w to 1.1.7

**Closed** 2018-09-19 01:47 UTC
Labels: duplicate

**Comment by coreybutler** [comment] 2018-09-19 01:48
This is also (partially) a duplicate of #300.
