### ISSUE TITLE
[Issue]: Can't find nodejs downloaded

### ISSUE THREAD

**Issue by LynasTing** [coreybutler/nvm-windows#1200] opened 2024-12-30 07:36 UTC
### What happened?

I can't find nodejs download where.

### What did you expect to happen?

After the nodejs download is successful, i can see it from nvm list, and use it.

### Version

1.2.0 or newer (Default)

### Which locale?

Other Non-English

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
C:\Users\LynasTing> nvm debug
Running NVM for Windows with administrator privileges.

Windows Version:        10.0 (Build 22621)

NVM4W Version:          1.2.0
NVM4W Path:             D:\enviroment\NVM\nvm\nvm.exe
NVM4W Settings:         D:\enviroment\NVM\nvm\settings.txt
NVM_HOME:               D:\enviroment\NVM\nvm
NVM_SYMLINK:            D:\enviroment\NVM\nodejs
Node Installations:     D:\enviroment\NVM\nvm
Default Architecture:   64-bit
Mirrors:                No mirrors configured
HTTP Proxy:             none

Total Node.js Versions: 0
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
NVM_SYMLINK does not exist yet. This is auto-created when "nvm use" is run.

IPv6 is enabled. This has been known to slow downloads significantly.

No problems detected.

⚠️  We are currently building Author/Runtime to succeed NVM for Windows.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

Here is how i use it.
![image](https://github.com/user-attachments/assets/5d9f6036-d6c9-4286-94f2-61c1a119025f)

And i checked nvm settings.txt :
  root: D:\enviroment\NVM\nvm
  path: D:\enviroment\NVM\nodejs

**Comment by coreybutler** [comment] 2024-12-30 13:42
Duplicate of #1198.

**Closed by coreybutler** 2024-12-30 13:42 UTC
