### ISSUE TITLE
`nvm use` not working

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#786] opened 2022-04-14 14:32 UTC
**Issue:**

`nvm use` is not working correctly. See errors:

```
C:\>nvm install 10
Version 10.24.1 is already installed.

C:\>nvm use 10
node vv10.24.1 (64-bit) is not installed or cannot be found.
C:\>nvm use 10.24.1
exit status 5: Access is denied.

exit status 5: Access is denied.
```

**How To Reproduce:**

1. `nvm install 10`
2. `nvm use 10`
3. See error
4. `nvm use 10.24.1`
5. See error again

**Expected Behavior:**
It should work.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: latest mainstream. Don't know, don't care, not relevant.

**Additional context:**
A workaround exists, which is to start the command prompt with elevated privileges **AND** type in the fully qualified version number. This should not be neccesary - nvm should ask for privileges whenever it needs them. The user should not have to know in advance when a program needs magical admin rights.

And yes, I know there are already a couple of issues on this problem. They are unclear on the exact problem, full of non-solutions, and useless "me too" (so please stop doing that, people).

**Comment by coreybutler** [comment] 2022-04-14 16:38
Duplicate of #708.

**Closed by coreybutler** 2022-04-14 16:38 UTC
Labels: duplicate

**Comment by thany** [comment] 2022-04-19 11:56
I stated I know about the other issues. They have gotten too spammy to make sense of it. But you insist, and presto: no solution. Just lots of "same here" and "me too" and superfluous screenshots.

You shouldn't be surprised to get a fresh new issue for the mess that #708 has become.

**Comment by coreybutler** [comment] 2022-04-19 13:13
The issue is already filed and there is already a PR to fix it. Adding the same issue again simply adds work.
