### ISSUE TITLE
initial open of cmd from install response screen error/use failed

### ISSUE THREAD

**Issue by lesliesmith** [coreybutler/nvm-windows#151] opened 2016-02-23 21:04 UTC
I just installed nvm-windows.  It appeared to install correctly to d:\myuserid\AppData\Roaming\nvm.  When I asked it to open a cmd.exe window, I landed in cmd.exe labeled windo in c:\windows\system32 which is where I would expect to land if I asked for a admin window but of course the settings.txt file was not found.  I found the nvm directory in the path.  The exact error is: ERROR open \settings.txt: The system cannot find the file specified. 

SESSIONNAME Console
The path was modified with nvm but the environment variables were not.  However they were listed in the user and system environment accessed from System Properties Control Panel and after rebooting these were visible from a command prompt.
NVM_HOME D:\myuserid\AppData\Roaming\nvm
NVM_SYMLINK C:\Program Files\nodejs

I don't know what was intended when you open that initial cmd.exe, but that error message deterred me from trying anything at that point. I started looking around and didn't try to use that initial window at all.

I expected that the start menu link for nvm would open up a usable admin window, but it just opens and closes a command prompt window.  It could open an administrator command prompt and stay open.

When I finally tried to use the nvm it worked with only a few miss directions. At first I typed the wrong command and got some really messy panic messages.

nvm install 32

Once I figured out I'd got the command wrong, I managed to install the latest 32 bit version of node.  The helpful suggestion about what to do next didn't work because 32 bit is not the default for my system.  It would have been more helpful to suggest I use the 32 bit version since that is what I installed.  

D:\>nvm install latest 32
Downloading node.js version 5.7.0 (32-bit)... Complete
Creating D:\LeslieSmith\AppData\Roaming\nvm\temp

Downloading npm version 3.6.0... Complete
Installing npm v3.6.0...

Installation complete. If you want to use this version, type

nvm use 5.7.0

D:\>nvm install latest 32
Downloading node.js version 5.7.0 (32-bit)... Complete
Creating D:\LeslieSmith\AppData\Roaming\nvm\temp

Downloading npm version 3.6.0... Complete
Installing npm v3.6.0...

Installation complete. If you want to use this version, type

nvm use 5.7.0

D:\>nvm use 5.7.0
node v5.7.0 (64-bit) is not installed.

D:\>nvm use 5.6.0
node v5.6.0 (64-bit) is not installed.

D:\>nvm use 5.6.0 32
node v5.6.0 (32-bit) is not installed.

D:\>nvm use 5.7.0 32
Now using node v5.7.0 (32-bit)

**Comment by coreybutler** [comment] 2016-02-25 15:46
I think this is a (generally) a duplicate of #22 and #63.

There is no start menu link, meaning you probably installed this on Windows 7/2012 or prior. The older OS may have generated that for you.

The initial cmd prompt that shows up is just a command prompt. There is an issue with the installer (I can't find the issue # quickly) that I don't have control over... it basically sets the `PATH` a split second after the command prompt opens. On some systems it works as expected, on some it doesn't. I filed an issue with InnoSetup, but the ultimate fix is a completely different installer (which I am working on).

I'm closing this since this refers to several previously mentioned issues. Feel free to catch me on the gitter channel if you have further specific questions.

**Closed by coreybutler** 2016-02-25 15:46 UTC
