### ISSUE TITLE
[Issue]: nvm install latest runtime error

### ISSUE THREAD

**Issue by TNSaturday** [coreybutler/nvm-windows#1026] opened 2023-09-08 10:23 UTC
### What happened?

I'm on Windows 11 22H2 22621.2134 trying to execute "nvm install latest" or "nvm install 20.6.0".

### What did you expect to happen?

I expected nvm to install specified node version for me.

### Version

1.1.10

### Which version of Windows?

Windows 11+

### Which locale?

Other Non-English

### Which shell are you running NVM4W in?

ConEmu

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x1398e180, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x1380e198, 0x6}, {0x509d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea
```

### Debug Output

```Shell
Running "nvm debug" just gives me the same output as simply running "nvm" (list of available commands).
```

### Anything else?

![image](https://github.com/coreybutler/nvm-windows/assets/27682909/f4728922-1178-4dac-8be1-acc7fdf8b516)

**Comment by coreybutler** [comment] 2023-09-08 14:40
You need to upgrade. This runtime error was resolved in NVM for Windows 1.1.11. Duplicate of #955.

**Closed by coreybutler** 2023-09-08 14:40 UTC
Labels: duplicate
