### ISSUE TITLE
confusing error message

### ISSUE THREAD

**Issue by iongion** [coreybutler/nvm-windows#65] opened 2015-06-07 12:44 UTC
maybe a minor issue, but a more proper error message would be nice(window 8.1- 64):
```
nvm install v0.12.4
```
Node.js vv0.12.4 is only available in 32-bit

but
```
nvm install 0.12.4
```
has no issue

**Comment by vkbansal** [comment] 2015-06-07 15:46
Duplicate of #37

**Comment by kRITZCREEK** [comment] 2015-06-17 10:02
:+1: just took me 10min to find this issue...

**Comment by rainabba** [comment] 2015-07-10 23:08
VERY confusing since `nvm list` reports `v0.12.4`.

**Comment by coreybutler** [comment] 2016-07-02 01:37
Fixed in 1.1.1

**Closed by coreybutler** 2016-07-02 01:37 UTC
