### ISSUE TITLE
nvm use - wrong version looked for: node vv* is not installed or cannot be found.

### ISSUE THREAD

**Issue by klodoma** [coreybutler/nvm-windows#822] opened 2022-06-19 20:33 UTC
Reported also here: https://github.com/nvm-sh/nvm/issues/2834, but it seems to be the wrong repo. 

#### Operating system and version:
Windows 11 x64

#### `nvm debug` output:

```sh
Running version 1.1.9.
```

#### `nvm ls` output:
<details>

```sh
PS C:\Users\andy> nvm ls

    18.4.0
  * 17.9.1 (Currently using 64-bit executable)
    16.15.1
    14.19.3
```
</details>

#### How did you install `nvm`?
With scoop. 
```sh
scoop install nvm
```

#### What steps did you perform?

```sh
nvm install 17
Version 17.9.1 is already installed.
nvm use 17
node vv17.9.1 (64-bit) is not installed or cannot be found.
nvm use 17.9.1
Now using node v17.9.1 (64-bit)
```

#### What happened?
```
node vv17.9.1 (64-bit) is not installed or cannot be found.
```

#### What did you expect to happen?

use node 17.9.1

**Comment by coreybutler** [comment] 2022-06-19 20:58
Duplicate of #708

**Closed by coreybutler** 2022-06-19 20:58 UTC
Labels: duplicate
