### ISSUE TITLE
`nvm use 4.x` should match the latest node 4 version

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [coreybutler/nvm-windows#539] opened 2020-05-17 14:54 UTC
### My Environment

Windows 10 version 1909, build 18363.836

### I'm using NVM4W version:

1.1.7

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [X] enhancement request

First of all, thank you, everyone, for maintaining NVM4W.

I believe that most of NVM4W users use it for backward compatibility support, therefore they don't really care that they're using node v4.9.1 or v4.9.0, they just want to test what they're working on on node v4.

Therefore what I am suggesting is that `nvm use 4` should try to find the latest minor, then find the latest patch for that version, which are installed.

`nvm use 4` finds 4.9, then between 4.9.0 and 4.9.1, it should use the latest.

The reason is that I've found myself almost always doing `nvm use 4`, getting nvm 4.0.0 is not installed, then I need to list the versions and find what minor, and patch version of node 4 I have.
I don't think people should have to remember all the `major.minor.patch` versions they have installed, instead nvm should help them by doing a best effort guessing what they meant.

**Comment by yume-chan** [comment] 2020-07-28 02:41
Or maybe `nvm use 4.x` for backward compatibility.

**Comment by DavyGuedes** [comment] 2020-09-29 03:09
It is a _must have_ feature in my opinion.

**Comment by Serializator** [comment] 2021-01-01 22:38
I believe this is a duplicate of #156, as the same behavior is discussed / described within it.

**Comment by hlovdal** [comment] 2021-03-18 12:20
This feature would be provided in the pull request mentioned in issue #623.

**Comment by coreybutler** [comment] 2021-09-15 17:10
Version expansion is available in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8 (and partially in 1.1.7).

**Closed by coreybutler** 2021-09-15 17:10 UTC
