### ISSUE TITLE
Setup file flagged up as adware by antivirus

### ISSUE THREAD

**Issue by coatesap** [coreybutler/nvm-windows#148] opened 2016-02-10 10:56 UTC
Not sure whether this is related to #133, but when I scan the setup file in ClamWin, it reports back as being infected with the message "Win.Adware.Eorezo-528 FOUND".

**Comment by coreybutler** [comment] 2016-02-13 06:30
I don't think this is related to #133. Most antivirus scans for file patterns, whereas in #133 the antivirus was actually changing the path (post-installation).

Doing a quick Google search revealed that ClamAV has been showing this error for many different setup files for different applications. It seems to be a false positive, specific to ClamAV and derivative works (which I believe ClamWin is). Since I think this is a very specific anomaly caused by ClamAV and not to antivirus in general, I'm closing this. Regardless, thank you for bringing it to attention.

If anyone sees this with a different antivirus in the future, please reopen.

**Closed by coreybutler** 2016-02-13 06:30 UTC
Labels: wontfix
