### ISSUE TITLE
Issue with setting node version

### ISSUE THREAD

**Issue by vigneshdv** [coreybutler/nvm-windows#30] opened 2014-12-24 15:12 UTC
I have installed nvm under the path:
**C:/Program Files/nvm**

After installing I ran the following command to install latest version of node:
**nvm install latest all**

I then ran the following command to set the node version I wanted to use:
**nvm use v0.10.34**

It showed the following error message
![error](https://cloud.githubusercontent.com/assets/5508006/5540016/8032eae0-8aed-11e4-8d7d-0832b4cfc426.png)

From the error message I think the issue is that the file path to nvm/node contains space i.e. _the space in the between "Program Files" of the file path where I have installed them_. 

Running the following command also threw a similar error:
![error1](https://cloud.githubusercontent.com/assets/5508006/5540075/133c47c8-8aee-11e4-81a0-7160a70c29f5.PNG)

I presume the file paths cannot handle spaces between them. A simple fix on this would be great.

**Comment by butaixianran** [comment] 2015-01-10 13:43
I have the same error on win7...
And I find out why.
The nodejs folder can have a space like "C:\Program Files". But, the folder of nvm-windows can't !

This problem is caused by changing the nvm instllation directory to "C:\Program Files\nvm".
Remove and re-install nvm-windows to some place like "c:\nvm" will be ok.

by the way, nvm-windows is much better than nvmw, really good job.

**Comment by gdvallance** [comment] 2015-01-10 16:18
I can confirm either the same bug, or s similar one. However, I can also confirm the work around by @butaixianran above works fine. 

From the errors I got, the execution of 'nvm use 0.10.35' got hung up on the fact that my Username is Grant D. Vallance ... A clue? 

Thank you @butaixianran and thankyou @coreybutler for a very useful piece of software. Appreciated.

**Comment by coreybutler** [comment] 2018-08-12 01:36
Resolved with PR #355.

**Closed by coreybutler** 2018-08-12 01:36 UTC
