### ISSUE TITLE
User names with spaces seem to break the batch files

### ISSUE THREAD

**Issue by GhostInTheMachines** [coreybutler/nvm-windows#480] opened 2019-10-23 12:58 UTC
### My Environment
- [x ] Windows 10

-
### I'm using NVM4W version:

- [ x] 1.1.7

### I have already...

- [x ] read the README to be aware of npm gotchas & antivirus issues.
- [ x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x ] verified I'm using an account with administrative privileges.
- [x ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
Expecting to be able to run nvm commands without errors.
Expecting to be able to run node commands without errors
Expecting to be able to run npm commands without errors

### Actual Behavior

Fill me in...
nvm install 12.11.1 seems to work correctly with the following response:
Downloading node.js version 12.11.1 (64-bit)...
Complete
Creating C:\Users\Dennis Kimble\AppData\Roaming\nvm\temp

Downloading npm version 6.11.3... Complete
Installing npm v6.11.3...

Installation complete. If you want to use this version, type nvm use 12.11.1

HOWEVER...When nvm use command is run, the following error is displayed:

PS C:\WINDOWS\system32> nvm use 12.11.1
exit status 1: 'C:\Users\Dennis' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce the problem:

Fill me in...
1. Installed nvm using Administrator privileges
2. Followed prompts, accepting the default installation location
i.e. C:\Users\Dennis Kimble\AppData\Roaming\nvm\
3. Installed node version 12.11.1 using the command nvm install 12.11.1
4. Attempted to run the first nvm use command

**Comment by holdsworth** [comment] 2019-10-27 14:16
+1

**Comment by JonasPuchinger** [comment] 2019-10-28 11:36
https://github.com/coreybutler/nvm-windows/issues/405#issuecomment-441353018

**Comment by 273299007** [comment] 2019-11-12 07:02
https://github.com/coreybutler/nvm-windows/issues/41
        When you have installed nvm and nodejs in C:\Program Files just use the following config in settings.txt and it should work.
        root: C:\PROGRA~1\nvm
        path: C:\PROGRA~1\nodejs

**Comment by coreybutler** [comment] 2019-11-18 04:01
Duplicate of https://github.com/coreybutler/nvm-windows/issues/41, fixed in PR #355.

**Closed by coreybutler** 2019-11-18 04:01 UTC
Labels: duplicate
