### ISSUE TITLE
nvm use command is giving error.

### ISSUE THREAD

**Issue by sunnysrivastava07** [coreybutler/nvm-windows#241] opened 2017-02-17 08:28 UTC
I have installed nvm and using this have a different version of node installed but while switching to another version it is giving error as shown below.

> Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Rajat Kukrety>nvm ls

  * 6.9.5 (Currently using 64-bit executable)
  4.2.6
  4.2.0

C:\Users\Rajat Kukrety>nvm use 4.2.6
exit status 1: 'C:\Users\Rajat' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Rajat Kukrety>

**Comment by naveedcs** [comment] 2017-02-17 14:40
I am having same issue I think if Users\Name has spaces like Users\name with spaces \ it gives this error

**Comment by coreybutler** [comment] 2017-02-17 19:15
Duplicate of #168.

**Closed by coreybutler** 2017-02-17 19:15 UTC
Labels: duplicate

**Comment by MdRasheedAhmed** [comment] 2020-07-21 14:33
https://github.com/coreybutler/nvm-windows/issues/161#issuecomment-576717795.

Refer this . It worked for me
