### ISSUE TITLE
NPM fails to download

### ISSUE THREAD

**Issue by leiamac** [coreybutler/nvm-windows#392] opened 2018-09-14 21:38 UTC
### My Environment

- [X] Windows 10

### I'm using NVM4W version:

- [X] 1.1.5

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [X] A standard shell environment (terminal/powershell)

### Expected Behavior

NPM to download correctly

### Actual Behavior

Installation log:
```
Downloading node.js version 10.10.0 (64-bit)...
Complete
Downloading npm version 6.4.1... Download failed. Rolling Back.
Rollback failed. remove C:\nvm\temp\npm-v6.4.1.zip:
The process cannot access the file because it is being used by another process.
Could not download npm for node v10.10.0.
Please visit https://github.com/npm/npm/releases/tag/v6.4.1 to download npm.
It should be extracted to C:\nvm\v10.10.0
```

The url for npm has changed and I believe that could be the problem. It's not "https://github.com/npm/npm/releases/tag/v6.4.1" but "https://github.com/npm/cli/releases/tag/v6.4.1".

I downloaded it manually but I believe it shouldn't be extracted to "C:\nvm\v10.10.0" but to "C:\nvm\v10.10.0\node_modules" instead. And If I extracted it as is, the name of the folder is cli-6.4.1 and I don't know if it is right or it should be cli or npm (without the version number).

Last node version I used was 8.11.1 and I didn't have a problem installing it a couple of month ago.

### Steps to reproduce the problem:

Runing `nvm install 10.10.0` in cmd

Thanks!

**Comment by B3zo0** [comment] 2018-09-14 21:46
Duplicate of #373
You should update nvm4w to 1.1.7

**Comment by leiamac** [comment] 2018-09-14 23:53
Thanks. Sorry for the duplicate, I tried to search the issue with different wordings but that one didn't pop up :(

**Closed** 2018-09-14 23:55 UTC

**Comment by B3zo0** [comment] 2018-09-15 09:28
@leiamac no worries :)

**Comment by tharinduhirantha** [comment] 2020-05-12 14:39
Solution:

- Download the relevant npm version from github.
- Then extract it to (C:\Users\tharindu\AppData\Roaming\nvm\v10.20.1\node_modules\npm)
- If npm bat file under (C:\Users\tharindu\AppData\Roaming\nvm\v10.20.1\) - (I have copied it from working node version)

**Comment by youyiqin** [comment] 2021-04-21 06:44
> Solution:
> 
> * Download the relevant npm version from github.
> * Then extract it to (C:\Users\tharindu\AppData\Roaming\nvm\v10.20.1\node_modules\npm)
> * If npm bat file under (C:\Users\tharindu\AppData\Roaming\nvm\v10.20.1) - (I have copied it from working node version)

It's not work for me.I uninstall current node and re-install it.
I installed node success,but npm failed because network timeout.Maybe we need to set the terminal proxy to solve it.

**Comment by sohmc** [comment] 2022-05-06 18:39
Sorry for resurrecting an old thread but wanted to provide another solution.

1. Download the relevent npm version from github (per tharinduhirantha)
2. Extract it somewhere convenient (Your Downloads directory is fine; we'll move it in a few steps)
3. The "root" extraction directory will be something like `cli-6.14.15`.  **RENAME** this directory to `npm`.
4. Move the "npm" directory to the "node_modules" directory within the version number of your `nvm` directory.  Using tharinduhirantha information, that would be `C:\Users\tharindu\AppData\Roaming\nvm\v10.20.1\node_modules`.  If the directory does not exist, go ahead and create it.
5. Your folder structure within the version directory should now have a `node_modules` directory and node.exe
6. Navigate to `node_modules\npm\bin`.  COPY the `npm.cmd` and place within the version directory of nvm, where you just saw node.exe

npm should now work as expected.  For details on why this works, you can review the `npm.cmd` file and see how it's looking for the npm/bin directory.
