### ISSUE TITLE
"use" fails if space in nvm installation path

### ISSUE THREAD

**Issue by GuerrillaCoder** [coreybutler/nvm-windows#249] opened 2017-02-28 12:50 UTC
On windows 10 64bit the "use <version>" doesn't work if the nvm installation path has a space in it.  I re-installed to path without space and it works but thought I would report it in case someone else runs into same problem.

**Comment by coreybutler** [comment] 2017-02-28 16:26
Duplicate of #41.

**Closed by coreybutler** 2017-02-28 16:26 UTC
Labels: duplicate
