### ISSUE TITLE
nvm list available

### ISSUE THREAD

**Issue by quantrpeter** [coreybutler/nvm-windows#637] opened 2021-04-11 19:11 UTC
Hi
   how to make "nvm list available" print more versions? or print all v10 versions?
thanks
Peter

**Comment by coreybutler** [comment] 2021-08-05 16:15
It can't list more than 10 currently, seeing as this is a hard coded limit. I'll mark this as an enhancement request.

**Comment by jemilehin** [comment] 2023-10-31 11:49
i got this error "Could not retrieve https://nodejs.org/dist/index.json." when i run command "nvm list available" on windows

**Comment by coreybutler** [comment] 2023-10-31 15:53
@jemilehin Check any firewall/proxy settings you have on your computer. Windows (or a proxy) may be blocking access, or maybe you just hit it during a maintenance window. I can confirm the link is valid and publicly accessible right now.

**Comment by artbindu** [comment] 2024-06-03 12:43
I have checked all node version
https://nodejs.org/dist/index.json
Where I can separate node LTS version as follows:
```
LTS version:
JSON.parse(req.response).filter(x => !(x.lts === false)).map(x => x.version)

NOT LTS Version:
JSON.parse(req.response).filter(x => x.lts === false).map(x => x.version)
```

But my question is, how to separate them `OLD Stable` & `OLD unstable` version ?

**Comment by artbindu** [comment] 2024-06-03 13:06
https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L883

This file is strictly showing only latest 20 data.

![image](https://github.com/coreybutler/nvm-windows/assets/44528087/3dafb67a-8d82-4c05-bafe-2bc0819f0ec6)

**Comment by coreybutler** [comment] 2024-06-03 16:27
Old stable is what LTS was previously. If you're using the JSON file, you can use the `lts` attribute. If `lts` is `true`, it's stable. If it's false, it's unstable.

**Comment by coreybutler** [comment] 2024-06-03 16:30
I'm closing this issue because I don't plan to update this feature in NVM for Windows. We have a completely new visual mechanism for presenting versions in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (both GUI and CLI).

**Closed by coreybutler** 2024-06-03 16:30 UTC
Labels: enhancement request, wontfix
