### ISSUE TITLE
Unable to easily uninstall NVM if it was installed by another user name

### ISSUE THREAD

**Issue by mfstanton** [coreybutler/nvm-windows#509] opened 2020-02-10 22:21 UTC
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

Run `nvm version` if you don't know.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by mfstanton** [comment] 2020-02-10 22:28
Version 8.1.0 One of my users installed it on a system I use and the install info goes into the ROAMING folder for that user. Windows will not allow me to uninstall it because I am not that user. It does however splash its start button on the global start menu.  The Settings Apps menu of Win 10 does not allow a process to be designated as administrator. What I wound up doing is going to the uninstall programme and right clicking on it to run it as Administrator. That got rid of the pesky bugger. Putting a programme like that in private data space is only asking for trouble for various reasons like security.

**Comment by coreybutler** [comment] 2020-02-11 16:37
First of all, that uninstallation process is dictated by the operating system. Windows is designed to prevent one user from removing another user's programs. It requires an admin to override that, by design... nothing NVM4W can do about that.

Second, did you mean NVM4W v1.1.8? i.e. the one in the master branch? Or were you referring to Node 8.1.0? The latest stable release of NVM4W is 1.1.7. I'm also unsure of what you're referring to with a start button on the global start menu.

Finally, the NVM4W installer provides an option for specifying the installation roots, so you can choose whatever you like. Whoever installed it would have to have explicitly chosen/confirmed the private data space.

I'm closing this since I'm not seeing any evidence of this being a bug. The experience seems to be more about how it's being used and the choices selected during installation. If there is an actual issue, please provide more detail and I'd be happy to re-open this.

**Closed by coreybutler** 2020-02-11 16:37 UTC

**Comment by mfstanton** [comment] 2020-02-11 17:49
You may do as you wish. I was using Node 8.1.0. The default mode was what the problems were because in my case the user who installed it put it up as available for all it blocked my ability to replace it as the administrator. The inexperienced user given administrator privileges notwithstanding should not have been able to do something that is not undoable by another administrator.  I did report the problem to Microsoft but their reaction will be that a package should not install itself in a folder that is not accessible. As it was the Apps settings gave the clue that the programme was installed and let me find it.
