### ISSUE TITLE
ERROR open \settings.txt: The system cannot find the file specified.

### ISSUE THREAD

**Issue by lloydjatkinson** [coreybutler/nvm-windows#945] opened 2023-03-15 16:19 UTC
**Issue:**
After installing nvm (from WinGet in this case) and before restarting the terminal, attempting to use nvm will fail.

Now, you might think that restarting the terminal is a simple action the user can do but when you are trying to automate the installation of a bunch of apps and developer tools, it's not a viable solution to restart the terminal.

Running nvm at this point will fail with the expected error:
```shell
nvm: The term 'nvm' is not recognised as the name of...
```

So the next step would be to invoke nvm directly, which fails with this error:
```shell
PS C:\Users\User> C:\Users\User\AppData\Roaming\nvm\nvm.exe install latest

ERROR open \settings.txt: The system cannot find the file specified.
```

**How To Reproduce:**
1. Use WinGet to install nvm `winget install --id=CoreyButler.NVMforWindows  -e`
2. Attempt to run nvm directly as the terminal session will not have the updated %PATH%
3. Get weird error about missing settings.txt

**Expected Behaviour:**

It should be possible to automate the installation of developer tooling including nvm without needing to restart the terminal and thus no longer be possible to automate.

**Screenshots:**
![image](https://user-images.githubusercontent.com/5633938/225373398-0dab8b3e-9199-4d93-ac4e-0b263f3eda6b.png)

**Desktop:**
 - OS: Windows 11 - not tried on Windows 10, probably the same.

**Additional context:**
* I also raised an issue here about the possibility of Windows Terminal or WinGet just doing the right thing and refreshing the environment variables: https://github.com/microsoft/winget-cli/issues/3077
* I saw this other issue with the same error, but the suggested fix of running as admin made no difference: https://github.com/coreybutler/nvm-windows/issues/929

If this is some hard to fix error, could it be possible to add an argument to nvm which accepts a path of the settings file to use?

**Comment by julian-shermis** [comment] 2023-03-16 00:37
I've noticed this same issue, but not using that installer. When I follow the guide to install the application manually, I am able to install it, however once I make commands on it, it gives me that same error. I've made sure the settings file has the correct root path, but still no luck so far. I'm glad I'm not the only one experiencing this issue. Sounds like something that was added recently that didn't account for other installation process besides using the main installer.

**Comment by coreybutler** [comment] 2023-03-16 03:44
I'm not sure how winget is doing things (I don't maintain that installer). I typically recommend people follow the [manual installation guide](https://github.com/coreybutler/nvm-windows/wiki#manual-installation) when attempting to automate installation.

In this case, you may just need to touch the settings.txt file or assure it can be read. Your screenshot shows the settings file, so I'm not sure why it's not recognizing it.

Is this a US English locale?

**Comment by julian-shermis** [comment] 2023-03-16 04:02
Corey, I'm also noticing the same issue and I've manually installed it. I've tried to use the command line as an administrator and still no luck.

**Comment by coreybutler** [comment] 2023-03-19 03:12
It should work with the `.txt` extension.

**Comment by JaxCoder** [comment] 2023-03-23 13:36
my settings.txt was created by the installer. I checked that it is UTF-8 and it is. 
   ERROR open \settings.txt: The system cannot find the file specified.
maybe its just being shown wrong, but I see "\settings.txt" and it makes me think it's looking for "\settings.txt", which is different than ".\settings.txt" so if the error is correct, it's trying to look for settings.txt in the root of the drive.

**Comment by lloydjatkinson** [comment] 2023-03-23 13:42
I'm on English UK ("International").

>  so if the error is correct, it's trying to look for settings.txt in the root of the drive.

I had the same thought too.

**Comment by coreybutler** [comment] 2023-03-23 16:03
Please check the value of the `NVM_HOME` environment variable, which should not be empty. With manual installations (which the winget installer is likely based on), this value may not be set. If that's the case, then @JaxCoder is likely correct that it's confusing the path to the settings file. If there is no `NVM_HOME`, the settings path is not generated correctly (https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L49).

**Comment by aequasi** [comment] 2023-04-15 00:39
This is also happening to me with a fresh install using the installer on Windows 11.

**Comment by coreybutler** [comment] 2023-04-21 14:44
This should be resolved by upgrading to v1.1.11. In v1.1.11, there is also a `nvm debug` command that will help identify any problems with reading your settings.txt.

**Closed as completed** 2023-04-21 16:25 UTC

**Comment by mikaelmello** [comment] 2023-05-03 00:23
Still encountering this issue on 1.1.11:

C:\Program Files\nvm>nvm debug

ERROR open \settings.txt: The system cannot find the file specified.

C:\Program Files\nvm>nvm --version
1.1.11

**Comment by chill389cc** [comment] 2023-05-18 19:17
I'm also running into this issue with nvm version 1.1.11.
It was working for weeks but all of a sudden is throwing this error for me.

**Comment by qozle** [comment] 2023-05-24 15:44
Also encountering this issue with nvm version 1.1.11.  I'm using InnoSetup.  

While the terminal is still open (hasn't been restarted yet), I've checked my environment variable values.  They are set correctly- as is my path, for both the user and system (admin).  This isn't using the manual install.  I can see the settings text document file in `C:/users/MYUSER/AppData/Roaming/nvm` directory.

I tried `nvm debug` and also got `ERROR open \settings.txt: The System cannot find the file specified.`.

**Comment by lloydjatkinson** [comment] 2023-05-24 17:26
I have been suspicious of that path since I made this issue. I'm fairly sure it's because of the missing a dot, this is trivially easy to reproduce, it's trying to look on the root of C:\.

![image](https://github.com/coreybutler/nvm-windows/assets/5633938/b204aa4a-c9db-4427-892c-f29b791217ac)


It needs to be `.\settings.txt` here:

```go
var home = filepath.Clean(os.Getenv("NVM_HOME") + "\\settings.txt")
```
https://github.com/coreybutler/nvm-windows/blob/c1a633745ccfcfaedff34fdc72d3ca368720f166/src/nvm.go#L52

**Comment by coreybutler** [comment] 2023-05-24 17:42
The issue is `NVM_HOME` is not recognized at runtime. If it were just `.\settings.txt`, it would only work in one specific directory.

In PowerShell, run `$env:NVM_HOME` to see if the variable is set correctly. It should look like the following: 

<img width="256" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/01b914ee-f192-4b0a-94d8-3aa99435490f">

**Comment by mikaelmello** [comment] 2023-05-24 17:42
On my case, the issue was not having reopened the terminal after installation so that NVM_HOME was set.

I had closed and opened new tabs but that does not trigger an environment reload on Windows I guess.

**Comment by coreybutler** [comment] 2023-05-24 18:00
@mikaelmello it depends on which app is running powershell. The tabbed tools typically don't reload the environment until the app is reopened (VS Code is the same way). I wish there were a clearer way to determine this behavior, but every shell app is different.

**Comment by qozle** [comment] 2023-05-26 18:10
I'm still struggling with this- trying to install nvm with Inno Setup.  

I've stepped through the install script I made in debug mode, and it's not finding the settings.txt file, even though the correct env variables are set, and they are present on the PATH (for system and user).  Are there any tricks for dealing with this, if you can't restart the terminal?

**Comment by mikaelmello** [comment] 2023-05-26 19:03
A slight improvement on the ux might be what other Linux projects do after a install on the terminal: printing the necessary commands to set the variables for this session.

**Comment by qozle** [comment] 2023-05-30 13:58
Unfortunately that wouldn't be a solution for us...the installer needs to be pretty much hands off, for our very not tech-savvy users.

I couldn't get this to install successfully using Inno Setup to create an installer.  It seems the issue boiled down to the environmental variables not being recognized.  They were set correctly, but just not from the terminal's perspective.  That is to say, I could find the environmental variables correctly set while clicking through windows settings, or viewing them in the registry, but when I used the `SET` command in the terminal that was doing the install...the environmental variables weren't set.

From that termainal, I could successfully call the `nvm` command without any passed arguments, however it failed with `ERROR open \settings.txt: The system cannot find the file specified` when using any `nvm` command (even `debug`).

**Comment by bitdeep** [comment] 2023-08-04 13:36
This error is because your current command line prompt does not have %NVM_HOME%, just close your command prompt and open it again and it should work.

**Comment by lloydjatkinson** [comment] 2023-08-04 14:41
Is this a serious reply or some AI generated reply? Please read original issue comment to understand this problem, it’s context, and usage with automation scripts and tools like winget.

**Comment by coreybutler** [comment] 2023-08-04 18:43
Actually @lloydjatkinson, @bitdeep's comment isn't necessarily off-base. If `NVM_HOME` isn't defined, NVM4W won't be recognized.

I'd also like to point out that I do't maintain the winget package, or the scoop package. The official installer, which was written with InnoSetup, should setup the environment variables appropriately. Upon completion of install, restarting the terminal may be required because InnoSetup ometimes has an untraceable race condition where the terminal launches/reloads before the environment variables are created. It's an annoying InnoSetup problem I have not found a solution to.

**Comment by bitdeep** [comment] 2023-08-04 19:26
> Is this a serious reply or some AI generated reply? Please read original issue comment to understand this problem, it’s context, and usage with automation scripts and tools like winget.

It's not ai generated ser, I just had this issue. So I decided to drop a come here to help people.

**Comment by Aikenwu** [comment] 2023-11-04 02:46
![image](https://github.com/coreybutler/nvm-windows/assets/12603935/9a03d9ef-4388-4d44-938b-b5e9e8c79e80)
![image](https://github.com/coreybutler/nvm-windows/assets/12603935/66c7cd14-2f15-4b16-a839-eed468372b1e)
for me , seem like use [edit the system environment variables] reset nvm_home path , the is correct.
![image](https://github.com/coreybutler/nvm-windows/assets/12603935/1032763c-e4fd-4aad-8be9-06cde8e09003)
