### ISSUE TITLE
Make URL to download npm configurable

### ISSUE THREAD

**Issue by baderbuddy** [coreybutler/nvm-windows#153] opened 2016-03-04 16:20 UTC
### My Environment

- [x] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [x] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

The ability to configure where npm is being downloaded from, in order to download from within the firewall, not needing to worry about proxy settings.

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by coreybutler** [comment] 2016-03-04 16:42
Closing as duplicate of #83.

**Closed by coreybutler** 2016-03-04 16:42 UTC
