### ISSUE TITLE
nvm use xxx , exit status 145: xx

### ISSUE THREAD

**Issue by zhoufanglu** [coreybutler/nvm-windows#707] opened 2021-12-14 11:29 UTC
`nvm version : 1.1.9;`
`install directory: C:\Users\86185\AppData\Roaming\nvm`

![image](https://user-images.githubusercontent.com/24451091/145989896-483be523-0b8d-4ec4-8741-e18ab247006c.png)

I have opened THE CDM using the administrator, why it's display status ` 145, 1`?

**Comment by coreybutler** [comment] 2021-12-16 01:50
Please see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145

Closing a duplicate of #701 and [related issues](https://github.com/coreybutler/nvm-windows/issues?q=is%3Aissue+145+is%3Aclosed).

**Closed by coreybutler** 2021-12-16 01:50 UTC
