### ISSUE TITLE
User folder with accented characters breaks nvm

### ISSUE THREAD

**Issue by nelero** [coreybutler/nvm-windows#941] opened 2023-03-07 16:59 UTC
**Issue:**
My folder user has accented characters.
When running nvm something, i got an error message : could not be found or does not exist. Exiting.

**How To Reproduce:**
1. Create a Windows user with accented character in it. The user folder will have the accented characters.
2. Open a terminal
3. Run nvm list
4. See error message

**Expected Behavior:**
Nvm should be found and running.

**Screenshots:**
```
C:\Users\Aurélien>nvm list
C:\Users\Aur�lien\AppData\Roaming\nvm could not be found or does not exist. Exiting.

No installations recognized.

C:\Users\Aurélien>
```

**Comment by coreybutler** [comment] 2023-03-09 17:40
Duplicate of #887.

**Closed by coreybutler** 2023-03-09 17:40 UTC
Labels: duplicate
