### ISSUE TITLE
[Feature request] Tag version

### ISSUE THREAD

**Issue by Andriy2** [coreybutler/nvm-windows#558] opened 2020-08-11 18:50 UTC
Any way to 'tag' installed versions like `install`

Usage behavior: 
```
nvm tag <version> [name]
```
```
nvm untag <version>
```
then any time to change version you don't have to remember version number but just type 
```
nvm use <name>
```

**Comment by Andriy2** [comment] 2020-08-11 18:51
If you have two node versions - it's okay to just `nvm list` and find needed version, but if you have different projects, some on LTS, some on Latest, some on elder node versions - it would be comfortable to use use tags instead of versions

**Comment by coreybutler** [comment] 2020-08-27 16:07
Duplicate of #478.

**Closed by coreybutler** 2020-08-27 16:07 UTC
Labels: duplicate
