### ISSUE TITLE
On uninstall nvm removes my node installation which was not installed using nvm

### ISSUE THREAD

**Issue by smasyutin** [coreybutler/nvm-windows#14] opened 2014-10-20 11:44 UTC
Install node
Install nvm
Confirm existing node installation to be controlled by nvm
Uninstall nvm
nvm is gone, node is gone.

**Comment by coreybutler** [comment] 2015-03-30 04:56
Since this wasn't really an issue (more expected behavior with an enhancement request), I'm closing.

**Closed by coreybutler** 2015-03-30 04:56 UTC
