### ISSUE TITLE
nvm use - to allow by major version

### ISSUE THREAD

**Issue by marlag** [coreybutler/nvm-windows#462] opened 2019-07-17 05:29 UTC
Feature request - to allow use version by major version only
`nvm use 10`
`nvm use 6`

So having f.e. 6.9.1 and 10.0.2 one no need to specify exact version. Should find the most matching one, so having 6.0.0 and 6.9.1 need to write `nvm use 6.0` or `nvm use 6.9` - however having multiple minor versions is rather rare case.

**Comment by coreybutler** [comment] 2019-07-19 23:01
Duplicate of #156.

**Closed by coreybutler** 2019-07-19 23:01 UTC
