### ISSUE TITLE
Proposition - install with "major" sufix

### ISSUE THREAD

**Issue by sosoba** [coreybutler/nvm-windows#515] opened 2020-02-25 07:17 UTC
nvm install 12.0.0
nvm install 13.0.0
nvm use 13.0.0

node --version 
v13.0.0

### New feature
node12 --version 
v12.0.0

node13 --version 
v13.0.0

**Comment by coreybutler** [comment] 2020-02-26 02:09
Duplicate of #402.

**Closed by coreybutler** 2020-02-26 02:09 UTC
Labels: duplicate
