### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by SteffenSunde** [coreybutler/nvm-windows#1020] opened 2023-08-22 20:54 UTC
### What happened?

`nvm use 18` fails with

```cmd
exit status 1:
exit status 1:
```

### What did you expect to happen?

# How to reproduce
1. Install Nodejs
2. Install nvm-windows
3. Open windows terminal as administrator
4. Run `nvm install 18`
5. Call `nvm use 18`

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
exit status 1:
exit status 1:
```

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\steff\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\steff\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\steff\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\steff\AppData\Roaming\nvm

Active Node.js Version: v18.17.1

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

Running `npm` produces no output

**Comment by coreybutler** [comment] 2023-08-22 21:02
duplicate of #1012

**Closed by coreybutler** 2023-08-22 21:02 UTC
