### ISSUE TITLE
Home Directories with multiple words not supported

### ISSUE THREAD

**Issue by chrisumbel** [coreybutler/nvm-windows#76] opened 2015-08-01 20:26 UTC
My home directory contains a space i.e. "C:\Users\Christopher Umbel"

When trying to do an "nvm use" the operation fails and my guess is that something somewhere in nvm requires quoting considering the error message contains the path up to, but not including the first space:

C:\Users\Christopher Umbel>nvm use 0.10.40 32
exit status 1: 'C:\Users\Christopher' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rmobis** [comment] 2015-08-02 13:37
Duplicate of #41?

**Comment by chrisumbel** [comment] 2015-08-02 18:58
Oops, pretty sure you're correct. Feel free to close.

**Closed** 2015-08-05 18:37 UTC
Labels: duplicate
