### ISSUE TITLE
NVM Always Fails

### ISSUE THREAD

**Issue by sirinath** [coreybutler/nvm-windows#213] opened 2016-10-17 05:05 UTC
I am using Win10 64 with running CMD as Admin but I am unable to use nvm. I get:

```
C:\>nvm install latest
Downloading node.js version 6.8.1 (64-bit)... Complete
Downloading npm version ... Download failed. Rolling Back.
Rollback failed. remove C:\Users\HP\AppData\Roaming\nvm\temp\npm-v.zip: The process cannot access the file because it is being used by another process.
Could not download npm for node v6.8.1.
Please visit https://github.com/npm/npm/releases/tag/v to download npm.
It should be extracted to C:\Users\HP\AppData\Roaming\nvm\v6.8.1
```

**Comment by nathfy** [comment] 2016-10-17 06:38
Same issue here, tried to uninstall and reinstall as Administrator cmd. Going to `https://github.com/npm/npm/releases/tag/v results in a 404` so assume this is the issue for nvm windows?

**Comment by Loghorn** [comment] 2016-10-17 08:09
The problem is that http://nodejs.org/dist/index.json doesn't list a version of `npm` and `nvm` fails in this case.
As a workaround you can manually install `npm` (the quickest method I found is to copy it from a `node 6.8.0` installation)

**Comment by sirinath** [comment] 2016-10-17 09:12
What do you do when you are installing the 1st time and you do not have npm to copy?

**Comment by Loghorn** [comment] 2016-10-17 09:38
`nvm install 6.8.0` works fine, then install 6.8.1 and copy nvm from 6.8.0

**Comment by coreybutler** [comment] 2016-10-17 18:00
Closing as a duplicate of #212 and #211. @Loghorn - nice workaround.

**Closed by coreybutler** 2016-10-17 18:00 UTC
Labels: duplicate

**Comment by markafitzgerald1** [comment] 2018-11-04 12:54
Related issue: if installing Node.js 10.7.0+ via `nvm` for Windows 1.1.6 and getting an `npm` download error much like the above an upgrade to the latest `nvm` for Windows (1.1.7) resolves the issue. The cause seems to be related to `npm` recently relocating their GitHub repositories, causing older versions of `nvm` for Windows to not be able to find recent (6.2.0+) versions of `npm`.

**Comment by NikhilNanjappa** [comment] 2019-02-28 11:33
Installing the latest version of `nvm` worked for me. If you're on windows, you can download it from here
https://github.com/coreybutler/nvm-windows/releases

**Comment by yashdabi** [comment] 2019-09-10 15:35
https://github.com/coreybutler/nvm-windows/issues/373#issuecomment-529991743
