### ISSUE TITLE
Bug on installing iojs ;-)

### ISSUE THREAD

**Issue by zxqfox** [coreybutler/nvm-windows#47] opened 2015-03-04 22:15 UTC
```
alex@LIGHTNIGHT ~
$ nvm install iojs
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0x648460, 0x7c947c)
        C:/Go/src/pkg/runtime/panic.c:279 +0xe9
_/C_/Users/Corey/Documents/workspace/Experiments/nvm/src/nvm/web.IsNode64bitAvailable(0x12520130, 0x4, 0x666180)
        C:/Users/Corey/Documents/workspace/Experiments/nvm/src/nvm/web/web.go:124 +0x1d6
main.install(0x12520130, 0x4, 0x666180, 0x2)
        C:/Users/Corey/Documents/workspace/Experiments/nvm/src/nvm.go:145 +0x279
main.main()
        C:/Users/Corey/Documents/workspace/Experiments/nvm/src/nvm.go:65 +0x599

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        C:/Go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        C:/Go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        C:/Go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        C:/Go/src/pkg/runtime/proc.c:1445
```

**Comment by coreybutler** [comment] 2015-03-04 22:38
Duplicate of issue #34.

**Closed by coreybutler** 2015-03-04 22:38 UTC
Labels: duplicate

**Comment by vkbansal** [comment] 2015-03-05 04:14
@coreybutler It would be good to add a note about no iojs support in README

**Comment by zxqfox** [comment] 2015-03-05 04:15
@coreybutler Oh, I'm actually create this about error `panic: runtime error: index out of range`, not about `iojs`. Anybody can pass there anything and got this error.
