### ISSUE TITLE
Disable UAC popup via setting

### ISSUE THREAD

**Issue by dieterp1** [coreybutler/nvm-windows#499] opened 2019-12-04 10:17 UTC
Hi,
nvm is working fine for me.
I'm using Windows 10 and with the Developer mode elevated rights are not longer needed for making symlinks. (see https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#oY8xkzvmiRr4M6ue.97)
It would be nice if there is an option to disable the elevation for creating symlinks.

**Comment by coreybutler** [comment] 2019-12-04 21:04
Closing as duplicate of #295.

**Closed by coreybutler** 2019-12-04 21:04 UTC
Labels: duplicate
