### ISSUE TITLE
uninstall nvm removes all versions of node?

### ISSUE THREAD

**Issue by MalcolmGC** [coreybutler/nvm-windows#163] opened 2016-04-29 20:37 UTC
Surprise! When I decided that I had no further use for nvm and clicked unins000.exe - I received a popup that stated this uninstall would remove all versions of nodejs!
I just want to remove nvm, not nodejs.

### My Environment

- [x] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by coreybutler** [comment] 2016-04-29 21:36
This is expected behavior. NVM4W acts like a proxy so you can switch versions. It does not install node the same way the node installer does (see the README for details on how it works). This is also why most people have to uninstall node before installing NVM4W, or nvm/nvmw/n/etc. Uninstallation should (and does) leave the system in the same state it found it.

**Comment by coreybutler** [comment] 2016-04-29 21:48
I didn't mean to close this.

Would it be valuable to you to be able to select a version of node to reinstall? The other option is NVM4W could move the contents of an existing version to a hard-coded folder instead of a symlink. For example, `C:\Program Files\nodejs` is a symlink to `%APPDATA%\nvm\vX.X.X` (i.e. whichever version is last specified by `nvm use`). The downside to this is there will be no uninstall option (since it was installed with NVM4W instead of the node installer).

These are options I could potentially add to the uninstaller. The second option is kind of dirty and won't necessarily play well with node upgrades, so there would be big red warning signs.

**Comment by ZaLiTHkA** [comment] 2016-05-10 12:00
If I could add my 2-cents worth here; I don't think NVM4W *should* actually be responsible for this.

From an environment configuration point of view, I would put NVM4W in the same group as Java build systems like Maven or Gradle; where you can either use an OS-specific setup package and have *that* configure the environment for you, or download an archive with the required files and configure the environment some other way, either manually or with an automation script. In this particular scenario, NVM4W itself takes care of the "automation script" side.

I know this is only my opinion, but since this is effectively an alternate way to achieve the same goal (with some extra functionality, just because we can) this really doesn't sound like a good plan at all...

**Comment by coreybutler** [comment] 2016-06-16 22:35
Closing due to inactivity.

**Closed by coreybutler** 2016-06-16 22:35 UTC
Labels: question
