### ISSUE TITLE
New Install Crashing

### ISSUE THREAD

**Issue by jamsoft** [coreybutler/nvm-windows#957] opened 2023-04-11 18:28 UTC
**Issue:**
Just found this tool as recommended on the Node site but it's immediately crashed. I've installed the latest nvm-windows version

**How To Reproduce:**

1. Install nvm-windows
2. Run CMD prompt as admin
3. nvm install latest

"nvm install latest
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x119a00e0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x1180e0c8, 0x6}, {0x489d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea"

**Expected Behavior:**
Should install node and npm

**Desktop:**
 - OS: Win11 64bit

**Comment by coreybutler** [comment] 2023-04-11 18:54
Duplicate of #955.

**Closed by coreybutler** 2023-04-11 18:54 UTC
Labels: duplicate
