### ISSUE TITLE
why i failed to run nvm?

### ISSUE THREAD

**Issue by chapgaga** [coreybutler/nvm-windows#52] opened 2015-03-23 22:22 UTC
what's wrong?

C:\Windows\system32>nvm

ERROR open \settings.txt: The system cannot find the file specified.

C:\Windows\system32>nvm list available

ERROR open \settings.txt: The system cannot find the file specified.

**Comment by coreybutler** [comment] 2015-03-23 22:34
Duplicate of #22.

**Closed by coreybutler** 2015-03-23 22:34 UTC
