### ISSUE TITLE
node vv16.17.1 (64-bit) is not installed or cannot be found.

### ISSUE THREAD

**Issue by basickarl** [coreybutler/nvm-windows#853] opened 2022-09-23 17:47 UTC
```
karl@basickarl MINGW64 /d/Development/cacodemon/console (main)
$ nvm version
1.1.9

karl@basickarl MINGW64 /d/Development/cacodemon/console (main)
$ nvm install lts
Version 16.17.1 is already installed.

karl@basickarl MINGW64 /d/Development/cacodemon/console (main)
$ nvm use 16
node vv16.17.1 (64-bit) is not installed or cannot be found.
```

Installed via chocolatey. Git Bash. Windows 10.

**Comment by bruno-barros** [comment] 2022-09-25 16:43
same here

**Comment by coreybutler** [comment] 2022-09-25 17:45
Duplicate of #708.

**Closed by coreybutler** 2022-09-25 17:45 UTC
