### ISSUE TITLE
add chocolatey support? 

### ISSUE THREAD

**Issue by Ashtonian** [coreybutler/nvm-windows#176] opened 2016-06-16 22:32 UTC
### My Environment
- [x] Windows 10
- [x] Windows Server 2012 R2
- [x] Windows Server 2016

### My issue is related to (check only those which apply):

- [x] installation 

### Expected Behavior

Can we get a chocolatey package? 

### Actual Behavior

It's not in chocolatey

### Steps to reproduce the problem:

try to install in chocolatey

https://chocolatey.org/packages?q=nvm - this will eventually be official via Microsoft's OneGet https://github.com/OneGet/oneget which will also be a part of the windows app store. This would be nice because theoretically at that point we could use gulp to bootstrap install choco - then this, then update to the latest npm on a new dev box.

**Comment by coreybutler** [comment] 2016-06-16 22:33
Please read the issues before posting. This is the 8th duplicate of #17.

**Closed by coreybutler** 2016-06-16 22:33 UTC
Labels: duplicate
