### ISSUE TITLE
exec: "elevate.cmd": executable file not found in %PATH%:[Issue]: 

### ISSUE THREAD

**Issue by wei63w** [coreybutler/nvm-windows#1069] opened 2023-11-30 08:06 UTC
### What happened?

![image](https://github.com/coreybutler/nvm-windows/assets/10754887/e31e75e3-cbb4-4d16-9461-cdab4a18a443)

### What did you expect to happen?

normail to use

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
PS C:\Users\xxx> nvm debug
Running NVM for Windows with administrator privileges.

管理员: Windows PowerShell
Windows Version: 10.0 (Build 22621)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\xxx\wyc\myNvm\nvm\nvm.exe
NVM4W Settings:     C:\Users\xxx\wyc\myNvm\nvm\settings.txt
NVM_HOME:           C:\Users\xxx\wyc\myNvm\nvm
NVM_SYMLINK:        C:\Users\xxx\wyc\myNvm\nvm\nodejsx
Node Installations: C:\Users\xxx\wyc\myNvm\nvm

Total Node.js Versions: 2
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
NVM_SYMLINK does not exist yet. This is auto-created when "nvm use" is run.

IPv6 is enabled. This can slow downloads significantly.
If you are experiencing npm problems, check the npm mirror (https://npm.taobao.org/mirrors/npm/) to assure it is online and accessible.

PROBLEMS DETECTED
-----------------
The following Node installations are invalid (missing node.exe): v11.15.0 - consider reinstalling these versions


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
PS C:\Users\xxx>
```

### Debug Output

```Shell
none
```

### Anything else?

none

**Comment by Edge-coordinates** [comment] 2023-12-16 11:21
> @wei63w how did you install this? You're missing a file that ships with the official installer.

I ran into the same problem with the NVM I installed with scoop

```powershell
PS C:\EDGE\LightReader> nvm install 16.20.2
Version 16.20.2 is already installed.
PS C:\EDGE\LightReader> nvm use 16.20.2    
exec: "elevate.cmd": executable file not found in %PATH%:
PS C:\EDGE\LightReader> scoop update nvm
nvm: 1.1.12 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

**Comment by Edge-coordinates** [comment] 2023-12-16 11:22
> @wei63w how did you install this? You're missing a file that ships with the official installer.

I ran into the same problem with the NVM I installed with scoop

```powershell
PS C:\EDGE\LightReader> nvm install 16.20.2
Version 16.20.2 is already installed.
PS C:\EDGE\LightReader> nvm use 16.20.2    
exec: "elevate.cmd": executable file not found in %PATH%:
PS C:\EDGE\LightReader> scoop update nvm
nvm: 1.1.12 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

**Comment by filipworksdev** [comment] 2023-12-18 16:26
I can confirm reverting to 1.1.12 fixes the issue. I will hold it at that version

**Comment by coreybutler** [comment] 2023-12-22 14:34
I'm closing this because it appears to be a problem with the Scoop installer (which we do not maintain). `elevate.vbs` is shipped with the installer/updater.

@filipworksdev - I'm not sure what you're "reverting" from. Version 1.1.12 is the latest.

**Closed by coreybutler** 2023-12-22 14:34 UTC

**Comment by filipworksdev** [comment] 2023-12-22 18:45
> @filipworksdev - I'm not sure what you're "reverting" from. Version 1.1.12 is the latest.

reverting from scoop. In scoop you can install any version you want by specifying with @ like this  `scoop install nvm@1.1.11`

```
WARN  Given version (1.1.11) does not match manifest (1.1.12)
WARN  Attempting to generate manifest for 'nvm' (1.1.11)
Autoupdating nvm
Searching hash for nvm-noinstall.zip in https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-noinstall.zip.checksum.txt
Found: md5:8f8a25a8b7dd42297ffebcf9373811be using Extract Mode
Writing updated nvm manifest
Installing 'nvm' (1.1.11) [64bit]
.... 
'nvm' (1.1.11) was installed successfully!
```

Nvm 1.1.11 works perfectly where as the latest 1.1.12 does not. Hope that helps clear up what I am reverting.

**Comment by coreybutler** [comment] 2023-12-22 19:46
@filipworksdev got it, thanks for clarifying!

**Comment by Abiel1024** [comment] 2024-01-08 11:35
> > @filipworksdev - I'm not sure what you're "reverting" from. Version 1.1.12 is the latest.
> 
> reverting from scoop. In scoop you can install any version you want by specifying with @ like this `scoop install nvm@1.1.11`
> 
> Here is a sample output what you get when you install a specific version in this case 1.1.11
> 
> ```
> WARN  Given version (1.1.11) does not match manifest (1.1.12)
> WARN  Attempting to generate manifest for 'nvm' (1.1.11)
> Autoupdating nvm
> Searching hash for nvm-noinstall.zip in https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-noinstall.zip.checksum.txt
> Found: md5:8f8a25a8b7dd42297ffebcf9373811be using Extract Mode
> Writing updated nvm manifest
> Installing 'nvm' (1.1.11) [64bit]
> .... 
> 'nvm' (1.1.11) was installed successfully!
> ```
> 
> Nvm 1.1.11 works perfectly where as the latest 1.1.12 does not. Hope that helps clear up what I am reverting.
> 
> The issue is from scoop.

it works for me!

**Comment by coreybutler** [comment] 2024-01-22 18:44
You can't just run the exe without configuring several environment variables and setting up a few files. This is why there is an installer. The raw exe is for people who choose to [manually install](https://github.com/coreybutler/nvm-windows/wiki#manual-installation).

People are apparently assuming the "noinstall" option means you don't have to install the app. That is not the case. That option means "no installer included". Most people should use the official installer. Those who need to create mass deployment/silent installation options (i.e. deploy via Active Directory) are the target audience for the "noinstall" option.

**Comment by coreybutler** [comment] 2024-01-22 18:45
Additionally, most Windows environments need to restart the terminal window in order to recognize updates to the `PATH` and other environment variables.

**Comment by Panossa** [comment] 2024-01-23 02:18
@coreybutler 
1. I didn't run "just the exe". I used the installer, it found a node version and started managing it. It also added environment variables and so on.
2. The environment variables were added normally and I could use "echo %NVM_HOME" to get the path, but just running "nvm" said there is no exe with that name until I restarted Windows. That's a completely separate issue, I think. And probably one with Windows itself.
3. Version 1.1.12 (installed using installer) did not work whatsoever. Even just running "nvm" by itself did not work and produced the message in the original post here. Then I uninstalled it (normally) and installed 1.1.11 via its installer (also gotten from GitHub releases) and it worked flawlessly. Without doing anything else than running the installer.

**Comment by coreybutler** [comment] 2024-01-23 03:53
@Panossa - To clarify, did you install via Scoop (per the topic of this thread), _then_ attempt to install with the official installer from the releases (nvm-setup.exe in this repo)? It sounds to me like there is `%PATH%` confusion on your system, perhaps two instances of NVM4W conflicting with each other. Sometimes Windows will expand the `NVM_HOME` variable to the actual path when adding to `%PATH%`. Everything you're describing could be caused by this.

**Comment by ctao-1** [comment] 2025-01-26 04:10
以管理员身份运行cmd或powershell，then print"nvm use <version>",can resolve this problem.
