### ISSUE TITLE
nvm使用use 就会提示这个.

### ISSUE THREAD

**Issue by cyzaoj** [coreybutler/nvm-windows#490] opened 2019-11-17 02:12 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

PS C:\Windows\system32> nvm use 12.13.0
exit status 1: 'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)
### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Steps to reproduce the problem:

nvm-windows runs in an Admin Power Shell.

 nvm install 12.13.0
nvm use 12.13.0

PS C:\Windows\system32> nvm use 12.13.0
exit status 1: 'D:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

**Comment by coreybutler** [comment] 2019-11-17 22:19
I don't speak the language this issue is written in. If someone could translate, it would help.

**Comment by cyzaoj** [comment] 2019-11-18 02:51
> I don't speak the language this issue is written in. If someone could translate, it would help.

如果路径包含空格，执行命令会包错
If the path contains spaces, execute "nvm use 12.13.0"  will pack errors

**Comment by coreybutler** [comment] 2019-11-18 04:00
Thank you @cyzaoj . This is fixed in 1.1.8, which is unreleased, but exists in the master branch. See https://github.com/coreybutler/nvm-windows/pull/355.

Closing as a duplicate of https://github.com/coreybutler/nvm-windows/issues/41.

**Closed by coreybutler** 2019-11-18 04:00 UTC
Labels: duplicate
