### ISSUE TITLE
2022-12-04: Add DisplayVersion key in the registry.

### ISSUE THREAD

**Issue by lcmuniz** [coreybutler/nvm-windows#894] opened 2022-12-04 12:51 UTC
I would like NVM to make the version number available in the Windows Control Panel. The WinGet package manager needs this information to know when to update the software. I think there is a registry key called DisplayVersion that WinGet checks.
Thank you.

**Comment by coreybutler** [comment] 2022-12-04 14:14
Duplicate of #851. This already exists in v1.1.10.

**Closed by coreybutler** 2022-12-04 14:14 UTC
