### ISSUE TITLE
Install the same Node version several times

### ISSUE THREAD

**Issue by piotrowski** [coreybutler/nvm-windows#270] opened 2017-05-12 12:00 UTC
First: Thank you so much for creating nvm-windows, it makes handling Node on Windows so much easier.

One common use case for having multiple `node` installations it when you develop or test a CLI tool that has to be installed globally via `npm`. Right now the only way to have multiple of these installed at the same time, is to have different node versions via `nvm-windows`. That of course is not optimal, as you can't really compare the two CLI installations as the node difference could cause problems or differences.

It would be great if the same version of node could be installed multiple times.

**Comment by coreybutler** [comment] 2017-05-12 21:40
It's not possible to have the same specific version of node installed multiple times and running simultaneously. There have been many requests for a "shared" node_modules directory, but there are so many issues with.

When developing a CLI tool, it's far more effective to use the [npm link](https://docs.npmjs.com/cli/link) feature. It operates in a similar fashion to nvm-windows, but was designed for npm (it was one of the inspirations for nvm-windows).

**Comment by piotrowski** [comment] 2017-05-12 21:46
> It's not possible to have the same specific version of node installed multiple times and running simultaneously.

Is it possible to install the same version mutliple times and **not** run them simultaneously? I thought about having to of them that I can switch like I switch between versions right now.

**Comment by piotrowski** [comment] 2017-05-12 21:53
Ohhhh, I just tried copying one of the versions into the same folder (adding " - Copy" at the end) and it at least recognized this and listed it in `nvm list`. `nvm use ...` also did something, unfortunately after that it still shows the previous non-Copy version as active. Probably `use` is doing more than just "loading node in the selected folder (with a v in front of it)"?

**Comment by coreybutler** [comment] 2017-05-12 22:28
Technically speaking, yes, it would be possible to have multiple installations of the same version as long as only one is active at any given time. However; it would require metadata instead of reading files, which adds complexity to the tool.

`nvm use` recreates a symlink to a specific node installation directory. The list of available node versions is detected by reading the directory list, which is why your copy shows up when running `nvm list` but doesn't work with the `use` subcommand. The `use` command does semver checking to assure a valid version of node is selected.

It'd be a total hack, but you might try copying the version you want and adding a prerelease tag syntax, i.e. something like `7.10.0-alpha` or `7.10.0-beta`. Those are semantically correct versions, but obviously they're your own copy, not a legitimate version of node. I have absolutely no idea what other kind of effects that may have, so it's definitely an "experiment at your own risk" suggestion... but it should be enough to fool nvm-windows into thinking it's a legit version to switch to. I still think you'd be better off with npm linking though.

I'm going to close this since this won't end up in nvm4w. However; I've made a mental note of your use case. I don't know if it's a widespread enough use case to end up in tool, but I am looking into hooks (similar to git pre-commit/post-commit) and a script launcher system that you might be able to use to accomplish this is a cleaner way. Those are on my roadmap for the next major release.

**Closed by coreybutler** 2017-05-12 22:28 UTC
Labels: enhancement, wontfix
