### ISSUE TITLE
Using unknown username

### ISSUE THREAD

**Issue by Tokimimo** [coreybutler/nvm-windows#925] opened 2023-02-04 17:08 UTC
**Issue:**
Cannot use NVM to install NodeJS

**How To Reproduce:**

1. Uninstall any manually installed nodejs version
2. Install NVM-Windows
3. Try running 'nvm install --lts'

**Expected Behavior:**

Installs latest Node LTS version

**Current Behavior:**
PS C:\Users\Tetsuga> nvm install node
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
main.versionNumberFrom({0x11c140b0, 0x4})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:496 +0x116
main.getVersion({0x11c140b0, 0x4}, {0xc69d26, 0x2}, {0x0, 0x0, 0x0})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:233 +0x367
main.install({0x11c140b0, 0x4}, {0xc69d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:273 +0xbb
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

**Comment by coreybutler** [comment] 2023-02-05 00:50
Duplicate of #919.

**Closed by coreybutler** 2023-02-05 00:50 UTC
