### ISSUE TITLE
runtime error upon `nvm install <characters>` with purely alphabetical characters

### ISSUE THREAD

**Issue by Einliterflasche** [coreybutler/nvm-windows#907] opened 2022-12-30 19:57 UTC
**Issue:**
Invoking the `install` command with at least one purely alphabetical argument (which is not `latest` or `lts`), such as `foo`, resolves in a runtime error. This is _not_ the case when the argument ends with a valid version number, such as `foo16`, however it does happen when the version number is unknown or the argument ends in a known alphabetical argument, such as `foolatest`. 

**How To Reproduce:**
1. Open command prompt
2. Enter `nvm install <unkown, purely alphabetical characters, optionally ending with a known version number>`
3. The following error is produced:

```
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
main.versionNumberFrom({0x1209c078, 0x7})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:496 +0x116
main.getVersion({0x1209c078, 0x7}, {0x12b9d26, 0x2}, {0x0, 0x0, 0x0})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:233 +0x367
main.install({0x1209c078, 0x7}, {0x12b9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:273 +0xbb
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea
```

**Expected Behavior:**
A message notifying of the unknown version should be produced, along with the help menu.

**Desktop:**
 - OS: `x64 Windows 10 Pro (10.0.19045 Build 19045)`
 - nvm-version: `1.1.10`

**Additional context:**
Please note that my account name is not `corey`, so this error message should be the exact same for all users.

**Comment by coreybutler** [comment] 2022-12-30 20:11
I can confirm the behavior and it should be fixed. However; this is a fairly low priority at the moment since a) most people know the version they're entering and b) this is the first time this has come up since the project started :)

Thank you for reporting it.

**Closed** 2023-01-27 03:57 UTC
Labels: bug, low priority
