### ISSUE TITLE
error when running 'nvm install latest'

### ISSUE THREAD

**Issue by peregringunn** [coreybutler/nvm-windows#958] opened 2023-04-12 15:40 UTC
**Issue:**
When attempting to install the latest version (19.9.0) of npm the following error occurs
 nvm install 19.9.0
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11c160b0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x11c160b0, 0x6}, {0x8b9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

**How To Reproduce:**
after running the nvm setup, enter 'nvm install latest' or 'nvm install 19.9.0' in powershell or cmd

**Expected Behavior:**
npm and node.js should install successfully

**Desktop:**
 - OS: Windows 10

**Comment by coreybutler** [comment] 2023-04-12 16:10
Please search/review existing issues before posting a new issue. This is the 4th duplicate of #955.

**Closed by coreybutler** 2023-04-12 16:10 UTC
Labels: duplicate
