### ISSUE TITLE
npm installation fails because "The filename or extension is too long."

### ISSUE THREAD

**Issue by stepbeta** [coreybutler/nvm-windows#340] opened 2018-02-21 14:03 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

Language is Italian

### I'm using NVM4W version:

- [ ] 1.1.6
- [x] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [x] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

In particular, the "non standard" shell is the bash included in VS code. The same problem presents itself even when using simple "Win+R -> cmd", though.

### Expected Behavior

Running `nvm install <version>` should install both node and npm correctly.

### Actual Behavior

Node is installed, but npm fails while installing. Output is the following:
```
C:\example>nvm install 9.5.0
Downloading node.js version 9.5.0 (64-bit)...
Complete
Downloading npm version 5.6.0... Complete
Installing npm v5.6.0...2018/02/21 14:45:28 mkdir C:\Users\stepbeta\AppData\Roaming\nvm\temp\nvm-npm\npm-5.6.0\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish: The filename or extension is too long.

C:\example>nvm use 9.5.0
Now using node v9.5.0 (64-bit)

C:\example>node
>
(To exit, press ^C again or type .exit)
>

C:\example>npm
"npm" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

C:\example>nvm install 8.9.4
Downloading node.js version 8.9.4 (64-bit)...
Complete
Downloading npm version 5.6.0... Complete
Installing npm v5.6.0...2018/02/21 14:46:42 mkdir C:\Users\stepbeta\AppData\Roaming\nvm\temp\nvm-npm\npm-5.6.0\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish: The filename or extension is too long.

C:\example>nvm use 8.9.4
Now using node v8.9.4 (64-bit)

C:\example>node
>
(To exit, press ^C again or type .exit)
>

C:\example>npm
"npm" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
```
<details>
  <summary>Folder structure is:</summary>

```
C:\Users\stepbeta\AppData\Roaming\nvm>tree
Elenco del percorso delle cartelle per il volume OS
Numero di serie del volume: xxxx-xxxx
C:.
├───temp
│   └───nvm-npm
│       └───npm-5.6.0
│           ├───.github
│           ├───bin
│           │   └───node-gyp-bin
│           ├───changelogs
│           ├───doc
│           │   ├───cli
│           │   ├───files
│           │   ├───misc
│           │   └───spec
│           ├───html
│           │   └───static
│           ├───lib
│           │   ├───auth
│           │   ├───config
│           │   ├───doctor
│           │   ├───install
│           │   │   └───action
│           │   ├───search
│           │   └───utils
│           │       └───completion
│           └───node_modules
│               ├───.bin
│               ├───abbrev
│               ├───ansi-regex
│               ├───ansicolors
│               │   └───test
│               ├───ansistyles
│               │   └───test
│               ├───aproba
│               ├───archy
│               │   ├───examples
│               │   └───test
│               ├───bin-links
│               ├───bluebird
│               │   └───js
│               │       ├───browser
│               │       └───release
│               ├───cacache
│               │   ├───lib
│               │   │   ├───content
│               │   │   └───util
│               │   ├───locales
│               │   └───node_modules
│               │       ├───ssri
│               │       └───y18n
│               ├───call-limit
│               ├───chownr
│               ├───cli-table2
│               │   ├───examples
│               │   │   └───screenshots
│               │   ├───lib
│               │   ├───node_modules
│               │   │   ├───colors
│               │   │   │   ├───examples
│               │   │   │   ├───lib
│               │   │   │   │   ├───custom
│               │   │   │   │   ├───maps
│               │   │   │   │   └───system
│               │   │   │   └───themes
│               │   │   ├───lodash
│               │   │   │   ├───array
│               │   │   │   ├───chain
│               │   │   │   ├───collection
│               │   │   │   ├───date
│               │   │   │   ├───function
│               │   │   │   ├───internal
│               │   │   │   ├───lang
│               │   │   │   ├───math
│               │   │   │   ├───number
│               │   │   │   ├───object
│               │   │   │   ├───string
│               │   │   │   └───utility
│               │   │   └───string-width
│               │   │       └───node_modules
│               │   │           ├───code-point-at
│               │   │           ├───is-fullwidth-code-point
│               │   │           │   └───node_modules
│               │   │           │       └───number-is-nan
│               │   │           └───strip-ansi
│               │   │               └───node_modules
│               │   │                   └───ansi-regex
│               │   ├───src
│               │   └───test
│               ├───cmd-shim
│               │   └───test
│               ├───columnify
│               │   └───node_modules
│               │       ├───strip-ansi
│               │       │   └───node_modules
│               │       │       └───ansi-regex
│               │       └───wcwidth
│               │           ├───docs
│               │           ├───node_modules
│               │           │   └───defaults
│               │           │       └───node_modules
│               │           │           └───clone
│               │           └───test
│               ├───config-chain
│               │   ├───node_modules
│               │   │   └───proto-list
│               │   │       └───test
│               │   └───test
│               ├───debuglog
│               ├───detect-indent
│               ├───dezalgo
│               │   ├───node_modules
│               │   │   └───asap
│               │   └───test
│               ├───editor
│               │   └───example
│               ├───find-npm-prefix
│               │   └───test
│               ├───fs-vacuum
│               │   └───test
│               ├───fs-write-stream-atomic
│               │   └───test
│               ├───gentle-fs
│               │   └───lib
│               ├───glob
│               │   └───node_modules
│               │       ├───fs.realpath
│               │       ├───minimatch
│               │       │   └───node_modules
│               │       │       └───brace-expansion
│               │       │           └───node_modules
│               │       │               ├───balanced-match
│               │       │               └───concat-map
│               │       │                   ├───example
│               │       │                   └───test
│               │       └───path-is-absolute
│               ├───graceful-fs
│               ├───has-unicode
│               ├───hosted-git-info
│               ├───iferr
│               │   └───test
│               ├───imurmurhash
│               ├───inflight
│               ├───inherits
│               ├───ini
│               ├───init-package-json
│               │   └───node_modules
│               │       ├───npm-package-arg
│               │       └───promzard
│               │           ├───example
│               │           │   └───npm-init
│               │           └───test
│               ├───is-cidr
│               │   ├───example
│               │   ├───lib
│               │   ├───node_modules
│               │   │   └───cidr-regex
│               │   │       └───lib
│               │   └───test
│               ├───JSONStream
│               │   ├───examples
│               │   ├───node_modules
│               │   │   ├───jsonparse
│               │   │   │   ├───examples
│               │   │   │   ├───samplejson
│               │   │   │   └───test
│               │   │   └───through
│               │   │       └───test
│               │   └───test
│               │       ├───disabled
│               │       └───fixtures
│               ├───lazy-property
│               └───libnpx
│                   ├───locales
│                   └───node_modules
│                       ├───dotenv
│                       │   └───lib
│                       ├───npm-package-arg
│                       ├───y18n
│                       └───yargs
│                           ├───lib
│                           ├───locales
│                           └───node_modules
│                               ├───camelcase
│                               ├───cliui
│                               │   └───node_modules
│                               │       ├───string-width
│                               │       │   └───node_modules
│                               │       │       ├───code-point-at
│                               │       │       └───is-fullwidth-code-point
│                               │       │           └───node_modules
│                               │       │               └───number-is-nan
│                               │       ├───strip-ansi
│                               │       │   └───node_modules
│                               │       │       └───ansi-regex
│                               │       └───wrap-ansi
│                               ├───decamelize
│                               ├───get-caller-file
│                               ├───os-locale
│                               │   └───node_modules
│                               │       ├───execa
│                               │       │   ├───lib
│                               │       │   └───node_modules
│                               │       │       ├───cross-spawn
│                               │       │       │   ├───lib
│                               │       │       │   │   └───util
│                               │       │       │   └───node_modules
│                               │       │       │       └───shebang-command
│                               │       │       │           └───node_modules
│                               │       │       │               └───shebang-regex
│                               │       │       ├───get-stream
│                               │       │       ├───is-stream
│                               │       │       ├───npm-run-path
│                               │       │       │   └───node_modules
│                               │       │       │       └───path-key
│                               │       │       ├───p-finally
│                               │       │       ├───signal-exit
│                               │       │       └───strip-eof
│                               │       ├───lcid
│                               │       │   └───node_modules
│                               │       │       └───invert-kv
│                               │       └───mem
│                               │           └───node_modules
│                               │               └───mimic-fn
│                               └───read-pkg-up
│                                   └───node_modules
│                                       ├───find-up
│                                       │   └───node_modules
│                                       │       └───locate-path
│                                       │           └───node_modules
│                                       │               ├───p-locate
│                                       │               │   └───node_modules
│                                       │               │       └───p-limit
│                                       │               └───path-exists
│                                       └───read-pkg
│                                           └───node_modules
│                                               └───load-json-file
│                                                   └───node_modules
│                                                       └───parse-json
│                                                           └───node_modules
│                                                               └───error-ex
│                                                                   └───node_modules
├───v8.9.4
│   └───node_modules
└───v9.5.0
    └───node_modules
```

 </details>

### Steps to reproduce the problem:

- Install nvm4w v1.1.5
- run `nvm install 9.5.0`

**Comment by davidbilge** [comment] 2018-02-23 13:07
A possible workaround for your problem is to install nvm in a "shorter path" than `C:\Users\stepbeta\AppData\Roaming\nvm`. If you use something like `C:\dev\nvm` your problem should go away.

If you do not want to re-install you can relocate your "root": Move all files except `nvm.exe`, `settings.txt`, `unins000.dat` and `unins000.exe` to `C:\dev\nvm`. Then, in `C:\Users\stepbeta\AppData\Roaming\nvm\settings.txt` change `root: ` accordingly (i.e. the line should become `root: C:\dev\nvm`). Now, remove the symlink `C:\Program Files\nodejs` which has now become invalid and on the command-line, do `nvm use <your-node-version>`. Everything should work now, including installing a newer node version.

**Comment by AnandDivakaran** [comment] 2018-02-23 18:38
@davidbilge The workaround of reinstalling nvm in a shorter path did not work for me.

**Comment by coreybutler** [comment] 2018-02-24 01:45
Duplicate of #289.

**Closed by coreybutler** 2018-02-24 01:45 UTC

**Comment by magicbruno** [comment] 2018-03-11 20:39
@davidbilge workaround did work for me. 
My suggestion: it's non necessa move files from nvm folder. You may use subst command:
`subst W: "C:\Users\YourUserName\AppData\Roaming\nvm"`
and then 
`root: N:\`
in `C:\Users\YourUserName\AppData\Roaming\nvm\setting.txt`
finally put the subst command in a batch file in Startup folder
