### ISSUE TITLE
nvm installlationn problem 

### ISSUE THREAD

**Issue by psiddharth709** [coreybutler/nvm-windows#304] opened 2017-09-25 16:42 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

![error](https://user-images.githubusercontent.com/25383528/30820110-933f39f2-a23e-11e7-9423-c6d2fbc8d2ed.png)

how to solve error?
please any idea share

**Comment by coreybutler** [comment] 2017-09-25 17:29
@psiddharth709 - this is the 4th time you've posted this. Please stop spamming the issues.

For the final time, run `nvm install latest --insecure`. Make sure you're not being blocked by a proxy or corporate firewall.

**Comment by psiddharth709** [comment] 2017-09-26 16:55
okkk i wil try

**Comment by Zorgatone** [comment] 2017-09-26 18:10
@coreybutler `nvm install latest --insecure` didn't work it sayed "--insecure is not a valid CPU architecture. Must be 32 or 64. I tried again with `nvm install latest 64 --insecure` and it worked

**Comment by coreybutler** [comment] 2017-10-04 17:30
@Zorgatone - which version are you running?

**Comment by Zorgatone** [comment] 2017-10-05 07:39
@coreybutler the 1.1.6 (https://github.com/coreybutler/nvm-windows/issues/305)

**Comment by lxiaoixi** [comment] 2017-11-08 04:51
![image](https://user-images.githubusercontent.com/20558919/32532155-470b0964-c483-11e7-865e-b1b8f04fcf9d.png)
I tried again with nvm install latest 64 --insecure,but it didn't worked

**Comment by khoa-nguyendang** [comment] 2024-01-25 04:18
step to reproduce.
1. machine has old nvm version (1.0.7)
2. install latest version nvm 1.1.12
3. uninstall old nvm version 1.0.7
4. active nvm 1.1.12 with nvm on
5. throw error Ciykd bit retrieve https://nodejs.org/....

**Comment by coreybutler** [comment] 2024-01-25 04:32
This issue is outdated and I am closing it.

@khoa-nguyendang when you upgrade, you don't need to uninstall the old NVM4W. It will be overwritten. Basically, you are installing 1.1.12 over 1.0.7, then "uninstalling"... but that would typically uninstall 1.1.12 because it was the latest one installed (you can't have more than one version of NVM4W at a time). You also don't need to run `nvm on`

**For anyone reaching here via Google:**

If you're getting an error about a TLS handshake timeout, it could be that your system isn't validating the certificate, or that the certificate has expired. The `--insecure` option bypasses the SSL certificate verification, so it's still an encrypted connection, just not verified.

For those seeing a link to `https://nodejs.org/dist/latest/SHASUM256.txt`, check your version. If you're using an older version of NVM4W and run something like `nvm install latest`, you'll get an error like the one @lxiaoixi displayed because `latest` is not a valid alias in older versions of NVM4W.

**Closed by coreybutler** 2024-01-25 04:32 UTC
