### ISSUE TITLE
nvm install xx should install latest minor version (xx.*) with this major number

### ISSUE THREAD

**Issue by Mart-Bogdan** [coreybutler/nvm-windows#596] opened 2020-12-18 03:12 UTC
When I run `nvm install 10` it downloads 10.0.0 version instead of downloading latest 10.*.

Expected behavior: download 10.23.0
Current behavior:  download 10.0.0

and downloading 0 releases from major would have lots of bugs.

This isn't logical and this controversy with [UNIX nvm](https://github.com/nvm-sh/nvm) behavior

Linx NVM is working correctly with semver

```
$ nvm install 10
Downloading and installing node v10.23.0...
Downloading https://nodejs.org/dist/v10.23.0/node-v10.23.0-linux-x64.tar.xz...
```

**Comment by Serializator** [comment] 2021-01-01 21:50
It seems that this should be the case already but isn't working properly. I installed Node 14 using `nvm install 14` and indeed it installed `14.0.0` not `14.15.3` as mentioned on [nodejs.org](https://www.nodjes.org).

https://github.com/coreybutler/nvm-windows/blob/061902359c9e8fa3334c4f4258a43048ae057c57/src/nvm.go#L193-L199

If I read the code correctly it seems that in case of `nvm install 14` that `version` is `14`, thus a length of 2 and not 1 (which makes the conditional to invoke `findLatestSubVersion` truthy).

Within `cleanVersion(version string)` a regular expression is used to determine the major, minor and patch given a version. What about using this to determine whether the end-user gave only a major version or not?
https://github.com/coreybutler/nvm-windows/blob/061902359c9e8fa3334c4f4258a43048ae057c57/src/nvm.go#L628-L644

I'm still in doubt whether this behavior is desired at all. If an end-user specifies both the major and minor version it (in my opinion) should still get the latest patch version. So... Is the conditional which is there at the moment even necessary?

Please let me know if I misinterpreted something, either in the description of the issue or the code!

**Comment by Serializator** [comment] 2021-01-01 22:39
I should've looked through other issues before commenting. I believe this to be a duplicate of #156, which describes the same behavior within it.

**Comment by Mart-Bogdan** [comment] 2021-01-03 11:19
There are module semver inside nvmw https://github.com/coreybutler/nvm-windows/blob/master/src/nvm/semver/semver.go#L184  but it seems is able to parse only full version:
```go
  // Split into major.minor.(patch+pr+meta)
  parts := strings.SplitN(s, ".", 3)
  if len(parts) != 3 {
    return nil, errors.New("No Major.Minor.Patch elements found")
  }
```

IDK, perhap package Masterminds/semver could be used?  It's `Constrainst`s seems to cover this: https://github.com/Masterminds/semver#checking-version-constraints

But actually changing len with regex should do the work too.

Regarding #156 -- it seems reporting a crash if not full version is given, which is seems resolved.

**Comment by Serializator** [comment] 2021-01-03 23:15
#156 was originally created for the crash you mentioned. Reading though I also see talk about whether `nvm install 4` installs the latest minor and patch version or not and whether it should or not.

**Comment by coreybutler** [comment] 2021-01-04 20:53
Closing as a duplicate.

**Closed by coreybutler** 2021-01-04 20:53 UTC
Labels: duplicate

**Comment by Mart-Bogdan** [comment] 2022-09-06 20:35
It seems to work correctly now, at 
```
nvm --version

Running version 1.1.9.
```
