### ISSUE TITLE
nvm use <int> has incorrect error message 

### ISSUE THREAD

**Issue by elibroftw** [coreybutler/nvm-windows#779] opened 2022-03-30 01:53 UTC
**Issue:**

nvm can't find 17.8.0 if `nvm use 17` is supplied and also two v's show instead of one

**How To Reproduce:**
```
C:\WINDOWS\System32>nvm install latest
...
C:\WINDOWS\System32>nvm use 17
node vv17.8.0 (64-bit) is not installed or cannot be found.
C:\WINDOWS\System32>nvm use 17.8.0
Now using node v17.8.0 (64-bit)

C:\WINDOWS\System32>
```

**Expected Behavior:**
17.8.0 should be found and used

**Comment by coreybutler** [comment] 2022-04-07 13:53
Closing as a duplicate of #708.

**Closed by coreybutler** 2022-04-07 13:53 UTC
Labels: duplicate
