### ISSUE TITLE
`nvm use` won't match major version number only to installed version

### ISSUE THREAD

**Issue by jcairney** [coreybutler/nvm-windows#804] opened 2022-05-12 16:21 UTC
**Issue:**

With the Linux version of nvm, one can do:
```
$ nvm install 15
. . .
Now using node v15.14.0 (npm v7.7.6)
$ nvm install 16
. . .
Now using node v16.15.0 (npm v8.5.5)
$ nvm use 15
Now using node v15.14.0 (npm v7.7.6)
```

On Windows, when you install a version it is not automatically selected.  And when you use a version, it can't be referenced by just the major version number.
```
> nvm use 16.5.0
Now using node v16.15.0 (64-bit)
> nvm install 15
. . .
Installation complete. If you want to use this version, type

nvm use 15.14.0
> nvm current
v16.15.0
> nvm use 15
node vv15.14.0 (64-bit) is not installed or cannot be found.
```

However, specifying the full version number works as expected, following the install:
```
> nvm use 15.14.0
Now using node v15.14.0 (64-bit)
```

**How To Reproduce:**

Run the above commands in PowerShell.

**Expected Behavior:**

It would be nice if nvm switched to the version being installed.  That's usually what people want to do when they install a new version.

But the main reason I came to file is that I expected when typing `nvm use 15` that it would find v15.14.0 and use it.  I get the impression this was the intended functionality (when I type 15, it tells me about 15.14.0 anyway) but it appears to be failing to match the major version number to an installed version, even though there is one (or more sometimes!) that should match.

 - OS: Windows 11
 - NVM: 1.1.9

**Additional context:**
I am using a utility called gsudo to elevate to administrator as I run the NVM commands.  It is awkward to start PowerShell as administrator every time, and though I saw bug titles suggesting that NVM should raise UAC prompts, I find it doesn't, and both `nvm install` and `nvm use` fail without some form on intervention to make either the console or issued command run as administrator.
e.g.
```
> gsudo nvm use 15
node vv15.14.0 (64-bit) is not installed or cannot be found.
```

**Comment by coreybutler** [comment] 2022-05-12 21:22
Duplicate of #708, already resolved in https://github.com/coreybutler/nvm-windows/pull/709.

**Closed by coreybutler** 2022-05-12 21:22 UTC
Labels: duplicate
