### ISSUE TITLE
Problema npm 

### ISSUE THREAD

**Issue by joicemingorance** [coreybutler/nvm-windows#335] opened 2018-02-12 21:30 UTC
C:\Users\user>npm -v
5.6.0

C:\Users\user>ionic -v
module.js:540
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\ionic\bin\ionic:8:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

C:\Users\user>cordova -v
module.js:540
    throw err;
    ^

Error: Cannot find module 'nopt'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\src\cli.js:19:12)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

esse problema fica aparecendo:
module.js:540
    throw err;
    ^

Error: Cannot find module 'semver'

**Comment by slimeygecko** [comment] 2018-02-28 22:41
Duplicate of #302

**Closed** 2018-04-17 08:09 UTC
Labels: duplicate
