### ISSUE TITLE
'use' commond has no effect

### ISSUE THREAD

**Issue by yuu2lee4** [coreybutler/nvm-windows#113] opened 2015-11-19 04:50 UTC
nvm use v0.12.7
 no effect

windows 10 10586 64bit

**Comment by dizlexik** [comment] 2015-11-23 04:30
+1
Duplicate of #110, which is closed but with no actual resolution.

**Comment by maxdeviant** [comment] 2015-12-03 14:40
I ran into this issue too. It appears that the symlink is not being created properly.

I got around this by running the command manually:

```
mklink /D "C:\Program Files\nodejs" "C:\Users\maxdeviant\AppData\Roaming\nvm\v5.0.0"
```

Note that you may have to delete the target directory first and/or run the command in an administrator command prompt window.

**Comment by coreybutler** [comment] 2015-12-22 18:17
Problem in this particular case is the `v`. It should be `nvm use 0.12.7`. It may also be related to #110, but I also recommend double checking permissions when doing `nvm install x.x.x`.

**Closed by coreybutler** 2015-12-22 18:17 UTC
