### ISSUE TITLE
Error attempting

### ISSUE THREAD

**Issue by MarceloBonifazio** [coreybutler/nvm-windows#365] opened 2018-06-27 16:15 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

**Obs v1709**

### I'm using NVM4W version:

- [x] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

install any version of the node along with npm

### Actual Behavior

Install only the node, but the referent version of npm lowers, but it gets zipped in the tmp folder and the error appears

### Steps to reproduce the problem:

Any of the commands

```
C:> nvm install 6.14.3 // It's what I want work
C:> nvm install 6.14
C:> nvm install 6.8
C:> nvm install latest

```
The error:

```

C:>nvm install v6.8
6.8.0
Downloading node.js version 6.8.0 (64-bit)...
Complete
Downloading npm version 3.10.8... Error while downloading https://github.com/npm/npm/archive/v3.10.8.zip - Get https://codeload.github.com/npm/npm/zip/v3.10.8: dial tcp 192.30.253.121:443: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5b32f7]

goroutine 1 [running]:
_/C_/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm/web.Download(0x142d0150, 0x2e, 0x142db4c0, 0x3c, 0x147e66d0, 0x6, 0x0)
        C:/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm/web/web.go:67 +0x307
_/C_/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm/web.GetNpm(0x1421a721, 0x27, 0x147e66d0, 0x6, 0x3f)
        C:/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm/web/web.go:163 +0x21b
main.install(0x1429d9b8, 0x5, 0x642b6f, 0x2)
        C:/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm.go:260 +0x680
main.main()
        C:/Users/Corey/Documents/workspace/OSS/nvm-windows/src/nvm.go:76 +0xa78
```

**Comment by MarceloBonifazio** [comment] 2018-06-27 21:15
it was in my work environment that this error occurred, I tried to install it on my personal machine and it happened all right (I had to change the local installation folder of the executable node, my user name has space, and apparently this causes an error, rest is fine) I need to check on my work environment, but it may be that in the roamming folder I have not deleted the npm folder from the previous node installation, and this caused the error.

**Comment by coreybutler** [comment] 2018-09-04 20:57
Closing as a pseduo-duplicate of #369 and #373.

For anyone coming across this issue without finding help from the two issues listed about, double check any proxy settings and and node mirrors to make sure your network isn't preventing the download.

**Closed by coreybutler** 2018-09-04 20:57 UTC
