### ISSUE TITLE
2021-08-19: Always install latest version for the semver range specified for "install"

### ISSUE THREAD

**Issue by capaj** [coreybutler/nvm-windows#654] opened 2021-08-19 08:52 UTC
**Is your feature request related to a problem? Please describe.**
When I run this command
```
PS C:\Users\capaj> nvm install 16
16.0.0
Downloading node.js version 16.0.0 (64-bit)...
```
version 16.0.0 is installed

**Describe the solution you'd like**
install latest version in the semver range, so 16.7.0 at the time of this writing.

**Describe alternatives you've considered**

**Additional context**

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment] 2021-08-19 12:44
Duplicate of #402, #440.

**Closed by coreybutler** 2021-08-19 12:44 UTC
Labels: duplicate
