### ISSUE TITLE
nvm use [major-version] not seeing installed versions

### ISSUE THREAD

**Issue by drfish** [coreybutler/nvm-windows#837] opened 2022-07-21 16:23 UTC
**Issue:**
NVM use with just the major version is says that an installed version is not installed and cannot be found.

**How To Reproduce:**
Install two different major versions, I switch between node 16 & 14 for instance (64 bit on both but it may not matter).
When installing a major version it accepts `nvm install 16` and grabs the newest of that major version.
Then try to switch from one major version to another, say from 14 to 16 with the command `nvm use 16` instead of `nvm use 16.16.0`. 
`node vv16.16.0 (64-bit) is not installed or cannot be found.` This version is in fact installed on my machine so this should work.
It's also mangling the version number by adding an extra v, but that may or may not be a purely cosmetic problem _shrug_

**Expected Behavior:**
`nvm install 16` grabs the newest node-16 version & installs it. 
I expect `nvm use 16` to work the same way. At the very least, if there's only one version of node-16 installed, if there are multiple it would be _nice_ if it would pick the newest installed, but it making the user specify in that scenario might make sense so I leave that choice to you folks.

**Screenshots:**
![image](https://user-images.githubusercontent.com/5140255/180262507-6046c6d2-4aa2-42fd-835c-4103dabe3206.png)

**Desktop:**
 - OS: Win10 64-bit

**Comment by coreybutler** [comment] 2022-07-21 17:14
Duplicate of #708.

**Closed by coreybutler** 2022-07-21 17:14 UTC
Labels: duplicate
