### ISSUE TITLE
node vvx.x.x (64-bit) is not installed or cannot be found.

### ISSUE THREAD

**Issue by LikeDreamwalker** [coreybutler/nvm-windows#827] opened 2022-07-02 13:18 UTC
**Issue:**
While I install nvm and node, a weird thing happend:
> PS C:\Users\Dream> nvm list
16.15.1
14.19.3
PS C:\Users\Dream> nvm current
No current version. Run 'nvm use x.x.x' to set a version.
PS C:\Users\Dream> nvm use 16
node vv16.15.1 (64-bit) is not installed or cannot be found.
PS C:\Users\Dream> nvm use 14
node vv14.19.3 (64-bit) is not installed or cannot be found.
PS C:\Users\Dream> nvm use 15
node v15.14.0 (64-bit) is not installed or cannot be found.
PS C:\Users\Dream> nvm install 15
Downloading node.js version 15.14.0 (64-bit)...
Complete
> Creating C:\Users\Dream\AppData\Roaming\nvm\temp
> Downloading npm version 7.7.6... Complete
> Installing npm v7.7.6...
> Installation complete. If you want to use this version, type
> nvm use 15.14.0
> PS C:\Users\Dream> nvm use 15
> node vv15.14.0 (64-bit) is not installed or cannot be found.

Seems like there is a "double-v" issue, while nvm try to use an exist version of node, it execute vvx.x.x instead of vx.x.x. And when I try to use the real uninstalled version, it returns with vx.x.x, so I think there might be something wrong with nvm or my device.

**How To Reproduce:**
Don't know if this could reproduce on other devices:
nvm install 16 (or any version)
nvm use 16

**Expected Behavior:**
Use the expect version directly and return with vx.x.x like else.

**Desktop:**
 - OS: Windows 10

**Comment by coreybutler** [comment] 2022-07-02 14:41
Duplicate of #708.

**Closed by coreybutler** 2022-07-02 14:41 UTC
Labels: duplicate
