### ISSUE TITLE
Getting "exit status 1: 'C:\Program' is not recognized as an internal or external command" when switching versions

### ISSUE THREAD

**Issue by lnaie** [coreybutler/nvm-windows#168] opened 2016-05-12 12:18 UTC
I have installed v1.1.0 in "C:\Program Files\nvm". All good but when I'm trying to switch to a version I have installed I get:

```
C:\WINDOWS\system32>nvm use 5.10.1
exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by andrehNSFW** [comment] 2016-05-30 17:56
The problem is with the spaces in URL(C:\Program Files). Try to install the nvm directly in C:/ or in other folder without spaces in the PATH.

**Comment by lnaie** [comment] 2016-06-02 13:03
Yes, but that is :)).

**Comment by coreybutler** [comment] 2016-06-04 20:34
Duplicate of #41.

**Closed by coreybutler** 2016-06-04 20:34 UTC
Labels: duplicate

**Comment by enaldick** [comment] 2017-03-23 06:50
# windows

> move to path there without whitespace 

or 

>running cmd as administrator   
and then mklink it to the new path there without whitespace.

**Comment by rwadkins** [comment] 2017-07-14 15:05
One of my users is having the same problem.  However, moving nvm to another folder doesn't work for us, because our security policies don't allow us to run applications outside of Program Files or Program Files (x86) folders.   It would be helpful if the code allowed it to run in a directory with spaces.

**Comment by AlexandrYalovyy** [comment] 2018-05-16 10:26
Change root directory for version of nodes (without spaces)
Then You can install there node and use it
Example:
`nvm root C:\nodejs\nvm`
`nvm install 10.0.0`
`nvm use 10.0.0`

**Comment by JoshRosenstein** [comment] 2018-10-09 15:02
Issue is old but for anyone that lands here you can reinstall nvm as mentioned above,
Or use short path. Changing `C:\Program Files\nvm`  with  `nvm root C:\PROGRA~1\nvm`
Might also want to use shortPath for NVM_SYMLINK : `C:\Program Files\nodejs`  to ` C:\PROGRA~1\nodejs`

**Comment by havettaa** [comment] 2018-12-12 08:10
You have changed the default path during installation.
I uninstalled nvm, and installed it with default paths, all works fine.

**Comment by ChrisTranzynergy** [comment] 2020-10-22 18:01
So if I put a space in my name when I got the computer, I'm just screwed forever, huh?

**Comment by bhupender005** [comment] 2020-11-07 14:45
a better solution is : https://github.com/coreybutler/nvm-windows/issues/405

**Comment by zohar1000** [comment] 2021-02-13 14:16
@bhupender005 that's greate, better than all the other answers, thanks!

**Comment by VishwasGajawada** [comment] 2021-02-14 10:07
@bhupender005 Thanks for your neat risk-free solution

**Comment by valdezm** [comment] 2021-02-27 19:29
If you manually move the nvm folder to for instance to `C:\nvm` you will need to:

Update the environment variable(`NVM_HOME`, both user and system ENV variables) so that your terminal recognizes the new location:

Once the environment variables are updated and you restart your terminal/command prompt, nvm should work, but the settings are still attached to the previous location, which will cause an error if you attempt to `nvm list` or mostly any other command.

Running `nvm root` will show that old location, all you have to do is set it with `nvm root C:\nvm`
(given the location you updated it to was `C:\nvm`, which is the same location you set the environment variable to).

Otherwise you will get errors saying that nvm is referencing the old path.

**Comment by pedroBaptistaDosSantos** [comment] 2021-05-02 22:51
You must install another program. I used volta and it solved my problem.

**Comment by kothariji** [comment] 2021-05-30 14:57
@

> a better solution is : #405
> 
> `Open Cmd, go to the Users directory, type dir /x and you will see the shortened version of the name of the users. (ALEXKA~1 in my case)`
> `Inside the nvm installation (AppData\Roaming\nmv in my case) there is a settings file, edit the first line and instead of having the space name put that shortened version and leave the rest the same like this :`
> `root: C:\Users\ALEXKA~1\AppData\Roaming\nvm`

@bhupender005 Thank you so much for this solution. Its working 🔥

**Comment by raiandexter0607** [comment] 2021-06-04 17:06
> 
> 
> The problem is with the spaces in URL(C:\Program Files). Try to install the nvm directly in C:/ or in other folder without spaces in the PATH.
I love you  friend

**Comment by lutherjohnworks** [comment] 2021-08-04 10:13
> a better solution is : #405
> 
> `Open Cmd, go to the Users directory, type dir /x and you will see the shortened version of the name of the users. (ALEXKA~1 in my case)`
> `Inside the nvm installation (AppData\Roaming\nmv in my case) there is a settings file, edit the first line and instead of having the space name put that shortened version and leave the rest the same like this :`
> `root: C:\Users\ALEXKA~1\AppData\Roaming\nvm`

this one solved my problem.

**Comment by lawweiliang** [comment] 2021-09-02 21:23
Jeus, I am testing here and there. Finally found out that the problem is space. Thanks @lutherjohnworks

**Comment by suman-saket** [comment] 2021-09-05 18:16
@bhupender005 Thankyou for your neat and clear solution .My issue was solved without any issue following your steps.

**Comment by carlosviniciusananias** [comment] 2021-09-22 02:10
> O problema é com os espaços na URL (C: \ Arquivos de Programas). Tente instalar o nvm diretamente em C: / ou em outra pasta sem espaços no PATH.

My issue was solved. Thanks!

**Comment by Alexey-Khlebnikov** [comment] 2021-12-24 23:16
Thank you very much

> a better solution is : #405
> 
> `Open Cmd, go to the Users directory, type dir /x and you will see the shortened version of the name of the users. (ALEXKA~1 in my case)` `Inside the nvm installation (AppData\Roaming\nmv in my case) there is a settings file, edit the first line and instead of having the space name put that shortened version and leave the rest the same like this :` `root: C:\Users\ALEXKA~1\AppData\Roaming\nvm`

This works for me too.

**Comment by riyastir** [comment] 2021-12-27 03:26
Spacing in the path is the problem

you can run

`nvm root` and find the root folder

then copy the contents to another folder without any spaces on the path

after that move the nvm root to that folder by running the command below (with full path)

`nvm root [path]`

**Comment by Anaizing** [comment] 2022-04-07 09:03
> C:\Program Files\nodejs

Thank you. I moved my nvm up to `C:\nvm` and my symlink was also `C:\Program Files\nodejs`
Which on windows can be checked via `control panel` click on `Users` then click on `Change my environment variable`

However it wasn't until i ran
`nvm off` `nvm on` that it all worked as expected. Thanks!!!

**Comment by zeeshansafdar48** [comment] 2023-03-23 07:09
> Spacing in the path is the problem
> 
> you can run
> 
> `nvm root` and find the root folder
> 
> then copy the contents to another folder without any spaces on the path
> 
> after that move the nvm root to that folder by running the command below (with full path)
> 
> `nvm root [path]`

Also if you are facing an error with the path, just write the path in single quotes.

**Comment by maitrithanh** [comment] 2023-06-16 14:03
Run git bash or cmd administrator. It worked for me.

**Comment by KaitoKid1612** [comment] 2023-06-27 07:30
Xoá node trên máy đi rồi cài lại từ đầu là được

**Comment by Zan-14** [comment] 2023-10-08 06:38
> a better solution is : #405
> 
> `Open Cmd, go to the Users directory, type dir /x and you will see the shortened version of the name of the users. (ALEXKA~1 in my case)` `Inside the nvm installation (AppData\Roaming\nmv in my case) there is a settings file, edit the first line and instead of having the space name put that shortened version and leave the rest the same like this :` `root: C:\Users\ALEXKA~1\AppData\Roaming\nvm`

Bruh, after trying many ways, this is the one for me.
