### ISSUE TITLE
weired error

### ISSUE THREAD

**Issue by wanghaisheng** [coreybutler/nvm-windows#808] opened 2022-05-17 02:49 UTC
**Issue:**

**How To Reproduce:**

**Expected Behavior:**

$ nvm use latest
exit status 145: Ŀ¼���ǿյġ�

exit status 1: ���ļ��Ѵ���ʱ���޷��������ļ���

dubo@LAPTOP-I2R9VG58 MINGW64 /d/Download/audio-visual
$ nvm root

Current Root: D:\Programs\nvm

windows 
install from nvm setup exe

**Comment by coreybutler** [comment] 2022-05-18 13:09
Duplicate of #717. Please see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145.

**Closed by coreybutler** 2022-05-18 13:09 UTC
