### ISSUE TITLE
nvm - install dir with spaces - nodejs no longer usable

### ISSUE THREAD

**Issue by IMTanuki** [coreybutler/nvm-windows#659] opened 2021-09-08 21:16 UTC
**Issue:**
I installed nvm in a dir that has spaces in it and granted nvm control over the current nodejs version (14.17.1). Now I can't:
- use the current nodejs version to run any node or npm commands in cmd or powershell;
- assign a different version of nodejs as the active version via nvm use.

And it seems that nvm cannot be uninstalled without also uninstalling all nodejs versions and -g packages.

**How To Reproduce:**
1. install nvm in D:\PROGRAMS - DEV - LANG - JS\NVM
2. nvm list returns 14.17.1 (the only nodejs version installed)
3. nvm use 14.17.6 correctly downloads 14.17.6
4. nvm use 14.17.6 returns the following error:
"exit status 1: 'D:\PROGRAMS' is not recognized as an internal or external command,
operable program or batch file"

At this point, any node commands return the following error:
"The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again"

Similar error for any npm commands.

**Expected Behavior**
I expected to be able to at least use current nodejs version (14.17.1).

**Screenshots**
N/A

**Desktop**
 OS: Win 10
 NVM for Windows: 1.1.7
 NodeJS (prior to nvm install): 14.17.1

**Additional context:**
Can you please advise:
1. is there any way to recover access nodejs v14.17.1 (without reinstalling)?
2. is there any workaround vis a vis changes to nvm's settings.txt?

**Comment by Iqon** [comment] 2021-09-14 08:25
Same Problem here. My Windows Account has a space and this is the default location for NVM.

**Comment by coreybutler** [comment] 2021-09-14 21:43
Duplicate of #611, resolved in v1.1.8.

**Closed by coreybutler** 2021-09-14 21:43 UTC
Labels: duplicate
