### ISSUE TITLE
Umlaute in Windows username prevent NodeJS installation

### ISSUE THREAD

**Issue by dominique-mueller** [coreybutler/nvm-windows#414] opened 2019-01-13 15:22 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [X] My Windows installation is non-English (it's german)

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [X] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

By default, `nvm` installs itself into the `AppData\Roaming` folder. In my case, it installs itself into `C:\Users\Dominique Müller\AppData\Roaming\...`. My user name contains an Umlaut ("ü" in the last name), yet I was expecting this not to be an issue.

### Actual Behavior

However, using `nvm` to install NodeJS doesn't work. It seems like the Umlaut ("ü") doesn't get recognized properly, and `nvm` complains about the folder not existing. I'm not sure if that's an issue within `nvm` or with the Windows installer for it.

![image](https://user-images.githubusercontent.com/7271961/51087132-48a2e100-174f-11e9-8e60-16a0092c48a5.png)

### Workaround

As a workaround, I was able to use `nvm root <path>` to change the root folder to a place where the path has no Umlaute. This works fine. However, people are probably expecting this to work without this change.

**Comment by mattlohkamp** [comment] 2019-07-18 20:29
how far out are we from the 1.1.8 release? I ask because I had a terrible moment of panic when I installed nvm and it immediately took node and npm out of commission for me... because it couldn't deal with the space in my user name, and therefore in the path to my user folder, on windows. (changing the root was the workaround that saved me though, for the record.)

**Comment by coreybutler** [comment] 2019-11-18 04:04
Closing, ultimately as a duplicate of https://github.com/coreybutler/nvm-windows/issues/41, fixed in PR #355. A 1.1.8 release is slow going since I'm having to rebuild the who release process (in Github actions).

**Closed by coreybutler** 2019-11-18 04:04 UTC
