### ISSUE TITLE
[Issue]: nvm install 14 fails

### ISSUE THREAD

**Issue by exhaler** [coreybutler/nvm-windows#1184] opened 2024-11-18 03:29 UTC
### What happened?

Unable to install latest version of node 14 or specific version 14.20.0. 

### What did you expect to happen?

installation to work

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
C:\Windows\system32>nvm install 14
Downloading node.js version 14.21.3 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v14.21.3\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v14.21.3\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v14.21.3 64-bit executable.

C:\Windows\system32>nvm install 14.20.0
Downloading node.js version 14.20.0 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v14.20.0\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v14.20.0\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v14.20.0 64-bit executable.
```

### Debug Output

```Shell
C:\Windows\system32>nvm debug
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\Test\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Test\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Test\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Test\AppData\Roaming\nvm

Total Node.js Versions: 1
Active Node.js Version: v23.2.0

IPv6 is enabled. This can slow downloads significantly.

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?
Also same scenario happens when trying to install any node version between 12 and 15 (inclusive)
```
PS C:\Windows\system32> nvm install 15
Downloading node.js version 15.14.0 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v15.14.0\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v15.14.0\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v15.14.0 64-bit executable.
PS C:\Windows\system32> nvm install 14
Downloading node.js version 14.21.3 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v14.21.3\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v14.21.3\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v14.21.3 64-bit executable.
PS C:\Windows\system32> nvm install 13
Downloading node.js version 13.14.0 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v13.14.0\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v13.14.0\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v13.14.0 64-bit executable.
PS C:\Windows\system32> nvm install 12
Downloading node.js version 12.22.12 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v12.22.12\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v12.22.12\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v12.22.12 64-bit executable.
PS C:\Windows\system32> nvm install 11
Downloading node.js version 11.15.0 (64-bit)...
Download failed. Rolling Back.
C:\Users\Test\AppData\Roaming\nvm\v11.15.0\node64.exe
Rollback failed. remove C:\Users\Test\AppData\Roaming\nvm\v11.15.0\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v11.15.0 64-bit executable.
```

**Comment by coreybutler** [comment] 2024-11-18 04:07
duplicate of #1179

**Closed by coreybutler** 2024-11-18 04:07 UTC
