### ISSUE TITLE
[Issue]: nvm use reports that exit status 1: The system cannot find the path specified. The system cannot find the file specified

### ISSUE THREAD

**Issue by vancfbruce** [coreybutler/nvm-windows#1012] opened 2023-07-19 11:09 UTC
### What happened?

I use scoop to install nvm,`nvm use` reports that exit status 1: The system cannot find the path specified.
The system cannot find the file specified.

### What did you expect to happen?

i expect `nvm use` success,

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

Asian

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
PS C:\Windows\system32> nvm debug
Running NVM for Windows with administrator privileges.

管理员: Windows PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         D:\Applications\Scoop\shims\nvm.exe
NVM4W Settings:     D:\Applications\Scoop\apps\nvm\current\settings.txt
NVM_HOME:           D:\Applications\Scoop\apps\nvm\current
NVM_SYMLINK:        D:\Applications\Scoop\persist\nvm\nodejs\nodejs
Node Installations: D:\Applications\Scoop\persist\nvm\nodejs

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by DaiWenqi** [comment] 2023-07-31 06:54
me too

**Comment by coreybutler** [comment] 2023-08-01 19:32
Did you run `nvm install x.x.x` where `x.x.x` is the version you want? You can't just run `nvm use x.x.x` if the runtime isn't installed yet.

**Comment by DaiWenqi** [comment] 2023-08-01 19:32
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vancfbruce** [comment] 2023-08-02 02:48
> Did you run `nvm install x.x.x` where `x.x.x` is the version you want? You can't just run `nvm use x.x.x` if the runtime isn't installed yet.

![image](https://github.com/coreybutler/nvm-windows/assets/26577347/6ae04484-bede-47d6-ba84-77327a9b8add)

**Comment by coreybutler** [comment] 2023-08-02 15:43
I believe the problem is the node installations are within your `NVM_SYMLINK`.

Notice `D:\Applications\Scoop\persist\nvm\nodejs` is your symlink root. You're then adding all of your installations to a directory called `nodejs` within that. Keep it separate. For example, your `NVM_SYMLINK` could be `D:\nvm4w\nodejs` or `C:\Program Files\nodejs` or anything that's not in `D:\Applications\Scoop\persist\nvm\nodejs`.

I'm starting to see this problem occurring regularly with those who install using Scoop. I recommend using the official installer. If you've already installed, you can modify the `settings.txt` file to update these directories.

**Comment by SteffenSunde** [comment] 2023-08-22 21:11
Hi, I have the same issue, but used the official installer. `SYSLINK_ROOT` points to `C:\Program Files\nodejs`.

Also, the output from PowerShell is
```cmd
exit status 1:
exit status 1:
```
i.e., no exit message. Weirdly though, it seems like my `cmd.exe` is also broken now, so my problem might run deeper.

**Comment by DaiWenqi** [comment] 2023-08-22 21:11
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by gnesher** [comment] 2023-09-15 13:21
$ nvm use 18.17.1
exit status 1: 'C:\Users\Guy' is not recognized as an internal or external command,
operable program or batch file.

using git bash

**Comment by DaiWenqi** [comment] 2023-09-15 13:21
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DaiWenqi** [comment] 2023-10-16 01:46
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by DaiWenqi** [comment] 2023-11-16 01:47
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by coreybutler** [comment] 2023-11-17 19:17
@DaiWenqi - according to Google translator, your messages are an "out of office" notice. It's spamming this issue. Can you please put an exception in your email processor to prevent holiday replies to Github issues?

根据谷歌翻译，您的消息是“外出”通知。这是垃圾邮件这个问题。您能否在您的电子邮件处理器中设置一个例外，以防止假日回复 Github 问题

**Comment by coreybutler** [comment] 2023-11-17 19:20
I'm closing this issue as the OP hasn't replied. @gnesher & @SteffenSunde - I assume you either found a resolution or moved on by this time. If not, see the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues).

**Closed by coreybutler** 2023-11-17 19:20 UTC

**Comment by joycehorn** [comment] 2024-11-02 19:01
> Hi, I have the same issue, but used the official installer. `SYSLINK_ROOT` points to `C:\Program Files\nodejs`.
> 
> Also, the output from PowerShell is
> 
> ```batchfile
> exit status 1:
> exit status 1:
> ```
> 
> i.e., no exit message. Weirdly though, it seems like my `cmd.exe` is also broken now, so my problem might run deeper.

I am now running through the same issue you had, with the exit status 1 on Powershell and my cmd.exe broken. Have been trying to find the issue for hours, but nothing yet. Were you able to solve this at all?

**Comment by DaiWenqi** [comment] 2024-11-02 19:02
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by coreybutler** [comment] 2024-11-03 14:05
@joycehorn check your variable names. There is no `SYSLINK_ROOT` in NVM for Windows. Perhaps you mean `NVM_SYMLINK`?
