### ISSUE TITLE
version 1.1.6 didn't fix spacing issue

### ISSUE THREAD

**Issue by pietrofxq** [coreybutler/nvm-windows#369] opened 2018-07-13 16:44 UTC
Issue still happening for me on windows 10.

![image](https://user-images.githubusercontent.com/6238029/42703372-cdc103b4-86a2-11e8-888e-58b93ab1583b.png)

**Comment by momocow** [comment] 2018-07-17 04:49
Also facing the same issue.
![image](https://user-images.githubusercontent.com/17778751/42797016-bc3dc1fc-89bf-11e8-884b-960bdbeb98bd.png)

**Comment by pkucherov** [comment] 2018-07-17 12:24
![image](https://user-images.githubusercontent.com/26567338/42817043-24e2d01e-89cd-11e8-93ac-c0d6e68800e8.png)

**Comment by andvarp** [comment] 2018-07-23 17:40
Same issue.
![image](https://user-images.githubusercontent.com/1946112/43093396-26ec5034-8e6d-11e8-9719-91b73c75c782.png)

**Comment by andvarp** [comment] 2018-07-24 14:16
I solved this issue by deleting the tool and installing it again with another installation path that doesn't include spaces on it, like this:
C:\nvm

**Comment by coreybutler** [comment] 2018-08-02 05:37
I'd be curious if https://github.com/coreybutler/nvm-windows/pull/355 fixes the issue. I've tried a few different means of fixing this in the past, but I'd like to merge this PR if it resolves the issue for folks.

**Comment by s-h-a-d-o-w** [comment] 2018-08-02 07:59
It seems like it fixes the issue for at least 2 people based on the reactions to my following comment: https://github.com/coreybutler/nvm-windows/issues/41#issuecomment-390732150

So I'd suggest people try out my fork and report back here, to (hopefully) get a larger sample size regarding people for whom the fix works. :)

**Comment by momocow** [comment] 2018-08-02 09:49
@s-h-a-d-o-w There are several problems occured while using `nvm v1.1.7` from your fork.

First of all, I tried to install the latest Nodejs, but `https://github.com/npm/npm/releases/tag/v6.2.0` returns 404 because the official npm repository has moved. I manually downloaded npm from `https://github.com/npm/cli/releases/tag/v6.2.0` and extracted it to `<nvm_path>\v10.8.0\node_modules\npm`. Then I tried to use it but failed with status 5.
![default](https://user-images.githubusercontent.com/17778751/43574020-addca14c-9675-11e8-9cba-efafa262e33a.png)

I was thinking if it was the problem caused by failed npm installation (also my manual installation was in a wrong way). I tried to install `node v6.14.3`. The installation worked like a charm but I failed to use it again with status 5.
![default](https://user-images.githubusercontent.com/17778751/43576609-5379aa40-967c-11e8-806a-c79869838494.png)

**Comment by s-h-a-d-o-w** [comment] 2018-08-02 10:04
Are this errors unique to my fork though or do you experience the same (or similar) issues in the original nvm-windows?

Because I didn't change any code related to the npm repository, so yes - `v10.8.0` doesn't work with my fork but I would wager that that has nothing to do with my changes.

As for `v6.14.3` - alright, I don't know about that one. I have a space in my nvm install path too but I just tried to install and use that version and it works for me.

**Comment by momocow** [comment] 2018-08-02 10:08
@s-h-a-d-o-w I've installed the original nvm-windows and have uninstalled it before using your fork. Not sure if it is the issue that there are still files or directories that were not cleaned up.

I should try to make a clean install of your fork.

**Comment by momocow** [comment] 2018-08-02 10:37
@s-h-a-d-o-w Your fork works! 😄 
![default](https://user-images.githubusercontent.com/17778751/43578434-5b17f9d2-9681-11e8-8900-9e5349a8d269.png)

It was my bad that I did not run the terminal as the admin while using `nvm use`.
Therefore the modification to the symlink failed.

**Comment by coreybutler** [comment] 2018-08-02 14:33
@s-h-a-d-o-w If you rebase your fork on the 1.1.7 tag (currently master), node 10.8.0+ should work. That issue has nothing to do with your fork.... but I fixed it last night.

**Comment by s-h-a-d-o-w** [comment] 2018-08-03 21:08
Rebase done, updated the executables in release 1.1.7. (So now even the `nvm version` information matches :wink: )

Can confirm that installing v10.8.0 works for me too now. :)

**Comment by coreybutler** [comment] 2018-08-14 02:12
#355 has been merged and appears to be working well. Expect it in the 1.1.8 release (available now in master).

**Comment by coreybutler** [comment] 2018-09-04 20:53
@euroclydon37 - right, as I said, it'll land in 1.1.8. You can build from source if you need this now.

**Comment by coreybutler** [comment] 2021-09-15 17:00
Resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Closed by coreybutler** 2021-09-15 17:00 UTC
