### ISSUE TITLE
Switch to version specified in .nvmrc file - feature request

### ISSUE THREAD

**Issue by rcollette** [coreybutler/nvm-windows#207] opened 2016-09-16 03:45 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...
- [ X] read the README to be aware of npm gotchas & antivirus issues.
- [X ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X ] verified I'm using an account with administrative privileges.
- [ X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Switch to version specified iin .nvmrc file.

### Actual Behavior
node v.0.0 (64-bit) is not installed.

### Steps to reproduce the problem:

run `nvm use` in a directory containing a .nvmrc file

**Comment by coreybutler** [comment] 2016-09-16 13:48
Duplicate of #16, #108, #128, #169.

**Closed by coreybutler** 2016-09-16 13:48 UTC
Labels: duplicate
