### ISSUE TITLE
[Feature]: support for a `./default-packages` file

### ISSUE THREAD

**Issue by martijnsenden** [coreybutler/nvm-windows#1194] opened 2024-12-12 13:34 UTC
### Description of the new feature / enhancement

[NVM supports having a list of default packages you want installed every time you install a new node version](https://github.com/nvm-sh/nvm?tab=readme-ov-file#default-global-packages-from-file-while-installing). You can just add the package names, one per line, to the file $NVM_DIR/default-packages. You can add anything npm would accept as a package argument on the command line. E.g.:

```
# $NVM_DIR/default-packages

yarn
```

I would love a similar feature in the Windows version, regardless of whether that is NVM4W or Runtime.

### Scenario when this would be used?

I need to have a package installed in each version by default, e.g. `yarn`.

**Comment by coreybutler** [comment] 2024-12-12 23:04
This won't be coming to NVM4W, but it is on our roadmap for Runtime. 

Our initial Runtime release aims to provide the same capabilities available NVM4W has today (i.e. make sure there aren't regressions before we add features). However; we designed Runtime from the very beginning to support this, so it will show up pretty quickly after the initial release.

I'm going to close this since it is concretely on our roadmap. NVM for Windows 1.2.0 will introduce our desktop notification system. It is possible to subscribe to "Author" updates - that is the main free product powering Runtime. I recommend subscribing to those alerts to be aware of when this (and other) features will be available.

**Closed by coreybutler** 2024-12-12 23:04 UTC
Labels: enhancement request
