### ISSUE TITLE
use other node version 

### ISSUE THREAD

**Issue by raidkarki** [coreybutler/nvm-windows#857] opened 2022-10-01 13:20 UTC
#When using **nvm use <version>** i get this problem 

_exit status 5: Acc�s refus�.
exit status 1: Impossible de cr�er un fichier d�j� existant._

**Comment by akahon** [comment] 2022-10-05 11:55
I have the same problem

**Comment by coreybutler** [comment] 2022-10-17 14:44
Duplicate of #717. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145

**Closed by coreybutler** 2022-10-17 14:44 UTC
Labels: duplicate
