### ISSUE TITLE
node command not found and NVM_SYMLINK not set properly by auto

### ISSUE THREAD

**Issue by yaochiqkl** [coreybutler/nvm-windows#243] opened 2017-02-21 15:03 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter]

### My issue is related to (check only those which apply):

- [x] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

I've installed nvm-windows succussfully through installer.
`node` and `npm` can be used in command

### Actual Behavior

`nvm use xxx` works well. 
it shows `Now using node v6.9.5 (64-bit)`
But `node` and `npm` doesn't work showing `command not found`

settings.txt
``` 
root: C:\Users\HP\AppData\Roaming\nvm
path: C:\Program Files\nodejs
```
when I check the `C:\Program Files\nodejs`, it points to the wrong version of node `C:\Users\HP\AppData\Roaming\nvm\4.2.1`,which I didn't installed by nvm but installed early before nvm installed.
And it never change after running `nvm use 6.9.5`.  
*** 
`NVM_SYMLINK` points to `C:\Program Files\nodejs`
but `C:\Program Files\nodejs` points to wrong version and never changed.
Tried through administrative privileges but in fail.

**Comment by coreybutler** [comment] 2017-02-22 19:47
Duplicate of #58.

**Closed by coreybutler** 2017-02-22 19:47 UTC
