### ISSUE TITLE
Enhancement: Publish to Chocolatey

### ISSUE THREAD

**Issue by mcandre** [coreybutler/nvm-windows#175] opened 2016-06-11 22:33 UTC
Chocolatey is a popular command line package manager for Windows, akin to Homebrew for Mac OS X. Could we please publish nvm-windows to Chocolatey to make installation more automated?

**Comment by coreybutler** [comment] 2016-06-11 22:49
Duplicate of #17.

**Closed by coreybutler** 2016-06-11 22:49 UTC
