### ISSUE TITLE
Use latest version flag

### ISSUE THREAD

**Issue by DasdWaller** [coreybutler/nvm-windows#605] opened 2021-01-26 16:36 UTC
In my work we use nvm4w and have 2 project with different node versions and need to switch often. It will very helpful for us to have a flag that don't need to add the full node version when need to use the `nvm use *`. This feature is great when you have to switch versions and want to avoid the full version name.

Example:
```
nvm list

15.6.0 (Currently using 64-bit executable)
15.2.1
14.15.4
14.15.1
14.15.0
```

`nvm use 15 -l` or `nvm use 15 --last`.
`nvm use 14 -l` or `nvm use 14 --last`.

**Comment by coreybutler** [comment] 2021-01-26 20:07
Closing as a duplicate of #156 and #539.

If companies are interested in new features to help their workforce, and are willing to pay to have them implemented, please reach out requesting a project engagement. There is a contact form available at https://butlerlogic.com/enterprise/.

**Closed by coreybutler** 2021-01-26 20:07 UTC
