### ISSUE TITLE
Error installing npm

### ISSUE THREAD

**Issue by bdeane96** [coreybutler/nvm-windows#491] opened 2019-11-25 09:49 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [-] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [-] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [-] read the README to be aware of npm gotchas & antivirus issues.
- [-] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [-] verified I'm using an account with administrative privileges.
- [-] searched the issues (open and closed) to make sure this isn't a duplicate.
- [-] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [-] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Install node 10.16.3 and npm 6.9.0

### Actual Behavior

Downloading node.js version 10.16.3 (64-bit)...
Complete
Downloading npm version 6.9.0... Error while downloading https://github.com/npm/cli/archive/v6.9.0.zip - Get https://github.com/npm/cli/archive/v6.9.0.zip: Proxy Authentication Required
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5c6eb0]

 

goroutine 1 [running]:
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.Download(0x14f7c6f0, 0x2d, 0x15370000, 0x38, 0x150a66e0, 0x5, 0x0)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:68 +0x240
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.GetNpm(0x14fce211, 0x24, 0x150a66e0, 0x5, 0x3e)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:163 +0x21b
main.install(0x14fbe078, 0x7, 0x660283, 0x2)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:268 +0x626
main.main()
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:78 +0x8cd

### Steps to reproduce the problem:

nvm install 10.16.3

[proxy is configured and i have attempted running the command with --insecure]
[i've attempted with multiple different nvm versions and i'm receiving the same npm error]

**Comment by coreybutler** [comment] 2019-11-25 23:01
The `--insecure` only applies to accepting TLS/SSL certificates without validating the certificate authority who issued it. It is not related to common proxies.

This issue is explicitly stating `Proxy Authentication Required`, meaning your proxy requires some sort of user credential. Bottom line is NVM4W can't reach the internet because the proxy is actively blocking it.

Depending on your proxy and how it handles auth, you may be able to to supply a proxy like `username:password@myproxy.com`. This would produce a basic authentication token, but that's the extent of what NVM4W can currently do. This sets the `Authorization` HTTP header of the request, which some proxies respect. However; NVM4W does _not_ set a `Proxy-Authorization` header. It's something that could potentially be added to a future version if demand is high enough.

I'm closing this since the issue is the proxy (not NVM4W) blocking requests, potentially resolvable by passing in credentials.

**Closed by coreybutler** 2019-11-25 23:01 UTC
