### ISSUE TITLE
download failure when suman

### ISSUE THREAD

**Issue by ystyle** [coreybutler/nvm-windows#100] opened 2015-10-14 02:25 UTC
PS Y:\Users\YSTYLE> nvm install 4.2.1
Downloading node.js version 4.2.1 (64-bit)... Error while downloading http://nodejs.org/dist/v4.2.1/win-x64//node.exe -
WSARecv tcp 192.168.199.246:60307: An existing connection was forcibly closed by the remote host.
Complete
Creating D:\Programming\nvm\temp

Downloading npm version 2.14.7... Complete
Installing npm v2.14.7...

Installation complete. If you want to use this version, type

nvm use 4.2.1

**Comment by ystyle** [comment] 2015-10-14 02:27
it's not only in this node version ,i had this problem install each version

**Comment by coreybutler** [comment] 2015-12-22 18:28
This can be caused by the Node.js servers terminating the connection or a faulty network. I believe a few Chinese users have encountered these problems. I'm closing this because there is already an open request (issue #97) for mirror support to better serve China.

**Closed by coreybutler** 2015-12-22 18:28 UTC
