### ISSUE TITLE
Ability to use nvm to launch a specific version of node.

### ISSUE THREAD

**Issue by tracker1** [coreybutler/nvm-windows#16] opened 2014-10-24 04:16 UTC
Although one could use batch files for this, and just accept that the symlink will swap around... it would be nice if one could `nvm (version) -run somescript` or similar for executing `npm` scripts with a specific version of node... with everything after the -run passed to node as parameters... `nvm 0.11.10 -run --harmony my-new-tool.js` as an example.. because I'm moving towards doing new projects with 0.11 and older ones still on 0.10, it would be nice to be able to set my services to use the appropriate version.

**Comment by mattheyan** [comment] 2016-05-11 20:16
Maybe this is a bad idea, but I'll throw it out there...

What about instead of having `%PROGRAMFILES%\nodejs` on the path, have another folder with `node.bat` and `npm.bat` files. They would search for an `.nvmrc` file from the current working directory and call that version of node or npm directly if found, or fall back to `%PROGRAMFILES%\nodejs` if not. I know I'm glossing over some technical details but it ***seems*** like that might be do-able.

Also, this wouldn't necessarily have to be a part of nvm proper, but it would be nice if it could be incorporated for convenience. It doesn't seem like this conflicts with nvm, and the majority of the value still remains in installing different versions of node and managing the symlink for the normal use cases.

Anyway, just an idea to consider.

**Comment by coreybutler** [comment] 2016-05-11 23:56
@mattheyan - Using a batch file still means wrapping node, so there will still be quirks and incompatibilities. The only way to guarantee node will run as intended is to run node directly, not through a wrapper. Unfortunately, I tried this with [node-windows](http://github.com/coreybutler/node-windows) and there have been more issues with wrapper workarounds than anything related to the project.

There are some interesting things happening with Go 1.7 that _might_, and I really stress the _might_, make this possible. However; that's still quite a ways from being released. I've been keeping my eyes on this for a while though (I would actually like to have this myself), and if a reliable solution becomes available, I'll definitely look into adding it.

**Comment by tracker1** [comment] 2016-05-12 18:31
A .cmd file should handle calling npm, or executing node with the appropriate stdin/stdout, as it's a pretty inherent part of windows... it actually sounds like an interesting idea.

**Comment by mattheyan** [comment] 2016-05-12 18:38
Yeah, I was thinking it could work in most cases. Node on windows does utilize bat/cmd file redirects a lot it seems. @coreybutler I don't doubt these quirks you mention exist, but I'm curious to hear what kind you've seen and whether they're common use-cases or obscure edge cases. Either way I understand why it would give you pause incorporating in nvm. And, like I mentioned before, there are other technical hurdles to overcome. But, I do think it would be really valuable if it could be done, if not in nvm proper then maybe in a companion tool.

**Comment by coreybutler** [comment] 2016-05-12 20:27
Well the `process.title` glitch I mentioned above is a big one from the node-windows community. 

However; the most prominent issues crop up around the file system. There are typically a bunch of issues with `__dirname` and `__filename`, as well as `process.cwd()` or anything else related to relative directory paths. I've received 100's of questions about this. The "wrapper" executable (winsw in the case of node-windows) runs from a different directory than node is installed in, so resolving filepaths can (and often do) differ. These issues can be worked around, but it causes alot of headaches for folks when their app works in one place and not in another, seemingly for no apparent reason. 

File system permissions can also be a challenge, as can passing in environment variables, all for the same reasons. When you wrap an executable, you're basically passing in a user to run it with too.

Remember, this project will no longer be Windows-only in the next release. In some experimentation within Docker, there have been other issues based on the file system. It has to do with how Docker is implementing volumes, so not directly an NVM4W thing, but I use it as an example of an emerging practice (containerization) that depends on an executable behaving the way it's supposed to.

When I initially released NVM4W, I exchanged a few thoughts with Sindre Sorhus, who maintains the awesome-node list. I tried to add both NVM4W and nvm to that list, but he objected to nvm (which uses a wrapper). The gist of it was too many people were experiencing glitches, so I'm sure there is stuff I haven't seen yet either.

**Comment by mattheyan** [comment] 2016-05-13 14:11
Thanks for the insight @coreybutler. I must admit I don't fully understand the nature of these issues, but it sounds like you've experienced pain from this in the past, so I see why you'd be hesitant to do this. I may revisit this at some point as a separate tool, and maybe I'll run into the same issues when I do (in which case you can say "I told you so" :P).

Feel free to close this issue since I think it was closed when I rehashed it - I would but it doesn't look like I can. Thanks again for the info and thoughts :)

**Comment by coreybutler** [comment] 2016-05-13 14:34
@mattheyan - If you do produce a companion tool, stay in touch. Like I said before, it is something I am also interested in. If there is a good companion tool, I'd certainly put up a link to it in the README here.

**Closed by coreybutler** 2016-05-13 14:34 UTC
Labels: enhancement

**Comment by jedmao** [comment] 2018-02-14 22:42
Works in PowerShell...
```powershell
nvm use $(Get-Content .nvmrc)
```

**Comment by nerdkid93** [comment] 2018-05-24 21:03
@jedmao 
## Command Prompt
```
for /f usebackq %i in (`type .nvmrc`) do nvm use %i
```

**Comment by rofrol** [comment] 2018-06-14 13:10
for git bash this works

```bash
$ nvm use `cat .nvmrc`
```

**Comment by FredyC** [comment] 2018-10-22 15:32
Regarding Powershell, I've tried adding this to my profile script to automate switching. It works, but there is a rather big downside that `nvm use` is not checking if the same version is already used and elevated prompt jumps in.

```
if (Test-Path .nvmrc) {
    nvm use $(Get-Content .nvmrc)
}
```

@coreybutler Would it be possible to add that check, even with some command line flag?

**Comment by coreybutler** [comment] 2018-10-22 15:47
`.nvmrc` is not supported, so a check won't do any good. `.nvmrc` is a an nvm for unix concept (different project).

**Comment by FredyC** [comment] 2018-10-23 09:39
@coreybutler That's not what I mean, you don't need to care about such file at all. What is needed is a check to `nvm use` and don't do anything if a specified version is currently selected. With that check in place and the small script above it's possible to mimic unix behavior fairly good. Whenever I would open Powershell in a folder containing `.nvmrc` it would get switched to that version.

I am aware it's not ideal, but it's surely better than to keep remembering version of Node for each project and manually switching it.

**Comment by coreybutler** [comment] 2018-10-23 14:53
@FredyC NVM4W doesn't run when a script is run (i.e. `node index.js`), so I'm not entirely sure when a check like that would even happen. The nvmrc concept is based on the premise that node is shimmed (i.e. called through a wrapper utility). NVM4W doesn't work that way. When you run `node.exe`, you're actually running Node directly... not a wrapper.

Additionally, your example only works on systems with powershell, which is not necessarily available or installed on all versions of Windows. While that's not difficult, it should highlight the fact there are all kinds of different Windows configurations to account for.

There have been alot of requests like this, focusing more on environment management than version management. The proposed solution is a [hooks](https://github.com/coreybutler/nvm-windows/issues/190) feature, currently on the [v2.0.0 roadmap](https://github.com/coreybutler/nvm-windows/projects/1). This would allow developers to run whatever scripts they want in response to NVM4W events, similar to git hooks.

**Comment by FredyC** [comment] 2018-10-24 07:32
Sorry, my explanation must be terrible if you are still not getting it :) Forget about `.nvmrc`, I don't expect NVM4W to do anything with that file.

What I am asking is simply extending `nvm use` command so it checks if the specified version is currently used and if its, it will just print message and exit. The current behavior is that it always tries to use a specified version causing a popup for elevated command.

Clear so far? I am not asking anything else from NVM4W. Reading `.nvmrc` a file will be done outside of its scope.

**Comment by marckassay** [comment] 2021-08-04 18:43
@reifnotreef replacing Start-Process line with the following seems to work:
```
 Invoke-Expression -Command "nvm use $version"
```

**Comment by tracker1** [comment] 2021-11-02 23:03
Could probably get the output from `node --version` and check against it in the `.nvmrc` file to only switch/elevate when necessary in the Powershell prompt/script.  For that matter, could probably create a powershell version of nvm that's much closer to the *nix (bash?) version.

**Comment by earonesty** [comment] 2022-08-03 14:15
without this feature, it breaks the use of nvm for ci/cd on systems that can handle more than 1 job.   kindof broken, imo.   changing global values is wack

**Comment by coreybutler** [comment] 2022-11-23 18:54
@ktzsolt you can still use NVM4W with two versions running at the same time... but you have to call the node.exe using the full path.

For example, consider this NVM4W installation:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/770982/203625283-8593e10b-60e3-4170-a783-dcc363f128cd.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/770982/203625605-cd8c5db9-fb57-48e5-ab56-fe8b1d99d7f1.png">

Your app needs to use the absolute path of the directory, or you could create a `node.cmd` or `node.bat` file in each app directory pointing to the appropriate version. This allows two versions to be used simultaneously.

**Comment by ktzsolt** [comment] 2022-11-23 21:37
@coreybutler Thanks for the quick reply, could you help me how I could run npm commands with this solution? Like `npm version` for start?

**Comment by coreybutler** [comment] 2022-11-23 22:47
@ktzsolt you figured it out... it's basically the same as the solution I mentioned above, but referencing npm instead of node:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/770982/203658823-42c84df8-bd58-4ed6-9a4a-a84c8481a60a.png">

**Comment by coreybutler** [comment] 2022-11-23 22:50
I've added the solution (above) to the [common issues wiki](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#how-can-i-use-two-different-versions-of-nodejs-at-the-same-time)

**Comment by ktzsolt** [comment] 2022-11-24 13:26
@coreybutler  What I also had to do is to run for the specific npm.cmd this command:
`\nvm\v10.12.0> .\npm.cmd config set scripts-prepend-node-path true`

After this I was able to run npm commands, but whitout this I would get this warning:

`npm WARN lifecycle npm is using D:\BuildTools\nvm\v10.12.0\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`

And subsequently many errors.

**Comment by raphaelsetin** [comment] 2024-03-13 21:49
### `nvm` still doesn't support this as of today, however, for others who may want the convenience, take a look at this other CLI tool called [Volta](https://github.com/volta-cli/volta).

It not only supports per-project version switching, but also supports multiple node versions running at the same time on different project directories. All of these features also work on Windows.

**Comment by luizxrs** [comment] 2024-07-08 18:13
This worked for me in windows, just make sure if everything else is working properly

paste this at the end of your `$profile` file

```powershell
function nvmFunc {
    param(
        [string]$Argument,
        [string]$Version = ""
    )

    if ($Argument -eq "install" -and $Version -eq "") {
        & nvm install (Get-Content .nvmrc)
    }
    elseif ($Argument -eq "use") {
        if ($Version -eq "") {
            $ver = Get-Content .nvmrc
        }
        else {
            $ver = $Version
        }
        & cmd /c nvm use $ver
    }
    else {
        & nvm $Argument
    }
}

Set-alias nvm nvmFunc

```

**Comment by rizqikazukun** [comment] 2024-08-05 15:55
Cool Thanks.

> This worked for me in windows, just make sure if everything else is working properly
> 
> paste this at the end of your `$profile` file
> 
> ```powershell
> function nvmFunc {
>     param(
>         [string]$Argument,
>         [string]$Version = ""
>     )
> 
>     if ($Argument -eq "install" -and $Version -eq "") {
>         & nvm install (Get-Content .nvmrc)
>     }
>     elseif ($Argument -eq "use") {
>         if ($Version -eq "") {
>             $ver = Get-Content .nvmrc
>         }
>         else {
>             $ver = $Version
>         }
>         & cmd /c nvm use $ver
>     }
>     else {
>         & nvm $Argument
>     }
> }
> 
> Set-alias nvm nvmFunc
> ```

**Comment by maxisam** [comment] 2025-02-09 20:02
script to work with both .nvmrc and .node-version, also avoid endless loop from above script 

https://gist.github.com/maxisam/9b5ece770c62e6a3ee978b4e671138d4
