### ISSUE TITLE
nvm use 18 not working

### ISSUE THREAD

**Issue by kaustubh135** [coreybutler/nvm-windows#836] opened 2022-07-20 18:39 UTC
**Issue:**
When using `nvm use 18` it fails to switch version and gives error `node vv18.6.0 (64-bit) is not installed or cannot be found.`.
From error I think nvm is trying to locate vv18.6.0 instead of v18.6.0 which is causing error as node v18.6.0 is installed in my system.

**How To Reproduce:**
Run `nvm use` and any initial version digit like 18 for v18.6.0.

**Expected Behavior:**
It is expected to use latest installed node version with same initial provided as default node version.

**Screenshots:**
![image](https://user-images.githubusercontent.com/90188030/180057762-2467af24-54cd-4eba-a125-c9de5358c5c2.png)

**Desktop:**
 - OS: Windows 11

**Comment by coreybutler** [comment] 2022-07-20 20:20
Duplicate of #708.

**Closed by coreybutler** 2022-07-20 20:20 UTC
Labels: duplicate
