### ISSUE TITLE
npm ERR! Error: ENOENT, readdir

### ISSUE THREAD

**Issue by mcandre** [coreybutler/nvm-windows#201] opened 2016-08-17 01:10 UTC
When `nvm install`'ed and `nvm use`'ed version 0.8.0 or 0.11.0, `npm` fails to find its man pages.

```
npm ERR! Error: ENOENT, readdir 'C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\man\man1'
npm ERR!  { [Error: ENOENT, readdir 'C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\man\man1']
npm ERR!   errno: 34,
npm ERR!   code: 'ENOENT',
npm ERR!   path: 'C:\\Users\\andrew\\AppData\\Roaming\\nvm\\v0.8.0\\node_modules\\npm\\man\\man1' }
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
npm ERR! cwd C:\Users\andrew\src\node-ios7crypt
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! path C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\man\man1
npm ERR! code ENOENT
npm ERR! message ENOENT, readdir 'C:\Users\andrew\AppData\Roaming\nvm\v0.8.0\node_modules\npm\man\man1'
npm ERR! errno 34
npm ERR! 34 errno
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\andrew\src\node-ios7crypt\npm-debug.log
npm ERR! not ok code 0
```

System:
- nvm-windows 1.1.1
- Windows 10 Professional x86_64

**Comment by coreybutler** [comment] 2016-08-22 15:26
Since these are version-specific, I believe the problem is in the downloaded npm/node installation files, not within NVM4W. I believe the may have been patched after the binaries were released, because building from source works with npm for these versions of node.

That said, I don't have time to cherry-pick through versions to rebuild/manage... and NVM can't rely on the end user having all of the dependencies required to build from source. I'll leave this open for investigation. If someone comes up with a clever solution, I'd certainly accept a PR.

**Comment by bladeoflight16** [comment] 2018-08-07 22:43
I don't think that NPM Was patched after the binaries were released. You get the same error if you reinstall NPM from the repository directly, pointing to a tag. For example, on Node 0.7.9 (Yes, I'm using an *ancient* version at the moment.) which comes with NPM 1.1.23, you can reinstall it using

```
npm install -g git://github.com/npm/cli#v1.1.23
```

Installation then works fine, but you get the error if you try to run `npm --help` after that. So it appears that they were built using some kind of default, built in process with NPM that generates a broken install, rather than however you were building it.

**Comment by coreybutler** [comment] 2021-12-16 02:48
Closing due to age.

**Closed by coreybutler** 2021-12-16 02:48 UTC
Labels: help wanted
