### ISSUE TITLE
[Issue]: Can't install any version. `nvm list available` lists nothing

### ISSUE THREAD

**Issue by samuel-andres** [coreybutler/nvm-windows#1065] opened 2023-11-22 16:21 UTC
### What happened?

Cant install any version. `nvm list available` lists nothing

### What did you expect to happen?

List available versions.

### Version

1.1.11

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
PS D:\
> nvm list available

|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |
|              |              |              |              |

This is a partial list. For a complete list, visit https://nodejs.org/en/download/releases
PS D:\
> nvm install 14.21.3

Version 14.21.3 is not available.

The complete list of available versions can be found at https://nodejs.org/dist/index.json
PS D:\
>
```

### Debug Output

```Shell
PS D:\
> nvm debug
Running NVM for Windows with administrator privileges.

Admin: D:\ - PowerShell 7.4 (15208)
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\samue\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\samue\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\samue\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\samue\AppData\Roaming\nvm

Active Node.js Version: v18.18.2

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by JuanDMeGon** [comment] 2023-11-22 16:28
I am getting exactly the same at this moment.

I already tried removing any prior existing Node version and reinstalling NVM, but still getting the same.

**Comment by JuanDMeGon** [comment] 2023-11-22 16:38
Additional notes.

By running` install latest` I get a verbose panic error.

![image](https://github.com/coreybutler/nvm-windows/assets/5510960/95a0d462-25c1-4b9e-b24d-a5fd069f2731)

Interesting to note the path it is using: `C:/Users/corey/OneDrive`

**Comment by samuel-andres** [comment] 2023-11-22 16:42
It's working now for me. Must been some kind of server error, if someone else can confirm I will close the issue.

**Comment by coreybutler** [comment] 2023-11-22 16:42
Duplicate of #1064.

**Closed by coreybutler** 2023-11-22 16:42 UTC
