### ISSUE TITLE
Installation paths with spaces fail with `nvm use`

### ISSUE THREAD

**Issue by Jameskmonger** [coreybutler/nvm-windows#337] opened 2018-02-16 13:41 UTC
### My Environment

Windows 10 Enterprise

### I'm using NVM4W version:

`1.1.5`

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Expected Behavior

`nvm use ...` should work regardless of install location

### Actual Behavior

`nvm use ...` fails if the path has spaces in it

When installed in `D:\Program Files\nvm`:

```
C:\Users\JamesMonger
λ nvm use 8.9.4
exit status 1: 'D:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### Steps to reproduce the problem:

Install `nvm` to a path with spaces in
Try to use `nvm use`

**Comment by KevinSnyderCodes** [comment] 2018-03-15 06:49
Maybe duplicate of #41. I was able to solve this issue using the workaround [here](https://github.com/coreybutler/nvm-windows/issues/41#issuecomment-85260068).

**Comment by coreybutler** [comment] 2021-09-15 17:01
Resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Closed by coreybutler** 2021-09-15 17:01 UTC
Labels: duplicate
