### ISSUE TITLE
Node.js v5.4.0 is only available in 32-bit.

### ISSUE THREAD

**Issue by vincentlws** [coreybutler/nvm-windows#130] opened 2016-01-11 09:50 UTC
when i try nvm install 5.4.0 
i get this : Node.js v5.4.0 is only available in 32-bit.

**Comment by coreybutler** [comment] 2016-01-11 14:15
Cannot recreate on Windows 10:

![image](https://cloud.githubusercontent.com/assets/770982/12235756/6e84ddfe-b83b-11e5-98c0-888135a9ebce.png)

**Comment by coreybutler** [comment] 2016-01-16 17:46
@vincentlws - Which version of Windows are you running?

**Comment by mm-gmbd** [comment] 2016-01-20 14:20
@coreybutler, getting the same issue. 

Running Windows 7 x64.

**Comment by mm-gmbd** [comment] 2016-01-20 14:36
Also, I managed to get myself into some sort of pickle trying to force this to work. First, I thought 32-bit executable were fine to run on 64-bit machines (not the other way around, though).

So, after getting the error:

```
nvm install 5.4
> Node.js v5.4 is only available in 32-bit.
```

I decided to run the following:

```
nvm install 5.4 32
> Downloading node.js version 5.4.0 (32-bit)... Download failed. Rolling back.
> Rollback failed. remove C:\Users\[userName]\AppData\Roaming\nvm\v5.4.0\node32.exe: The process cannot access the file because it is being used by another process.
>
> Could not download node.js v.5.4.0 32-bit executable.
```

So, I thought it was just simply not installed, but I figured I'd check to make sure:

```
nvm install 5.4 32
> Version 5.4.0 is already installed.
```

Hmm, so although it said it couldn't be installed, it then said it *was* installed, so I tried to force nvm to use it:

```
nvm use 5.4 32
> Now using node v.5.4.0 (32-bit)
```

Ok, great, now I'm using the latest version of Node. *Not* great.

```
npm install [package]
> 'npm' is not recognized as an internal or external command...
```

Okay, so it doesn't work, I'll just switch back to the 64-bit version that I had installed previously, so I tried to run `nvm list`. First, I got the following error popup:

![untitled](https://cloud.githubusercontent.com/assets/3329824/12451649/919829da-bf58-11e5-91d7-76e405addaf7.png)

But then, the following *did* output to the console:

```
nvm list
>
> 5.4.0
> 0.12.0
> 0.10.38
```

But, `nvm use` apparently doesn't know about the versions that are included in the list but are 64-bit:

```
nvm use 0.12.0
> node v.0.12.0 (64-bit) is not installed.
```

I'll go ahead and move the installed node 5.4.0 folder (`C:\Users\[userName]\AppData\Roaming\nvm\v5.4.0\`) as mentioned in the first output when I actually forced nvm to install the 32-bit version and report back...

**Comment by mm-gmbd** [comment] 2016-01-20 14:40
So, I moved the folder (`C:\Users\[userName]\AppData\Roaming\nvm\v5.4.0\`) into a backup folder elsewhere and ran the following:

```
nvm list
>
> 0.12.0
> 0.10.38
```

No error popup. So, I ran the following:

```
nvm use 0.12.0
> node v.0.12.0 (64-bit) is not installed.
```

Not sure what the problem is here, so I just decided to install that version again:

```
nvm install 0.12.0
> Downloading node.js version 0.12.0 (64-bit)... Complete.
```

Now, `nvm use 0.12.0` works. So, I'm back up and running again, but that was a bit of a headache -- hopefully helpful in the long run, though!

**Comment by mm-gmbd** [comment] 2016-01-20 14:42
Also, I'll try updating nvm itself, but at the time I was using the following version:

```
nvm version
> 1.0.6
```

**Comment by mm-gmbd** [comment] 2016-01-20 14:48
Okay, so I've updated to nvm 1.1.0, but and after re-configuring the proxy (that's one thing that doesn't seem to be copied during the update process, BTW), I now get the following error:

```
nvm install 5.4
> Version 5.4 is not available. If you are attempting to download a "just released version", ...
```

Is it saying that it's not available because it's not available in 64-bit? Confused now.

**Comment by mm-gmbd** [comment] 2016-01-20 14:59
I'm getting the `Version x.x not available...` error for *every* version. Not sure what the deal is... I'm going to try a complete uninstall and reinstall of the latest nvm and see if that gets things back up and working normally.

**Comment by javlc** [comment] 2016-04-19 14:28
I had similar problem, could not install node v4.4.3 or others above the 0.x version.
I was using nvm-windows -v 1.0.6.
Updating to nvm-windows to -v 1.1.0 helped overcome the issue.

**Comment by ravijangra** [comment] 2016-05-12 13:53
**SOLVED:** 

upgrading to nvm-windows to v 1.1.0 solved this issue.

**SOLVED**

**Comment by daoanhnhat1995** [comment] 2016-06-16 21:18
You just need to do 
nvm install 5.4 32 
It will download node 32 bit version instead of default 64

**Comment by coreybutler** [comment] 2016-07-02 01:20
I believe this has been resolved in the latest versions (1.1.0+). Feel free to reopen if anyone still experiences this.

**Closed by coreybutler** 2016-07-02 01:20 UTC

**Comment by taylorgoolsby** [comment] 2020-04-27 20:06
Although I don't get the error when I do `nvm install 12.16.2`, I do get the error when I do `nvm install lts/erbium`.

```
nvm install lts/erbium
lts/erbium.0.0
Node.js vlts/erbium.0.0 is only available in 32-bit.
```

I like using the code names because it will always download the newest minor and patch versions.
For now, specifying the exact version is good enough to work.

**Comment by hassankhan87** [comment] 2020-05-29 14:08
I am also getting an error, I have recently installed Microsoft updates maybe that break something.

```
nvm install --lts
--lts.0.0
Node.js v--lts.0.0 is only available in 32-bit.
```

Windows 10 x64 Version 2004 (OS Build 19041.264)
nvm -v 1.1.7

**Comment by gerardcsaperas** [comment] 2020-09-10 10:40
Getting the same error using Windows 10 and nvm 1.1.7:

```
$ nvm arch
System Default: 32-bit.
Currently Configured: 32-bit.

$ nvm install lts/dubinum
lts/dubinum.0.0
Node.js vlts/dubinum.0.0 is only available in 32-bit.
```

**Comment by BillyZeGame** [comment] 2020-10-19 23:12
Well... Getting the same... I'm quite a beginner trying to follow a tutorial, and hitting a wall after 2min30 of it (already spend 1h trying to work around...)

```
<me>@<me>-PC MINGW32 ~
$ nvm arch
System Default: 64-bit.
Currently Configured: 32-bit.

<me>@<me>-PC MINGW32 ~
$ nvm install express-generator
express-generator.0.0
Node.js vexpress-generator.0.0 is only available in 32-bit.
```

**Comment by coreybutler** [comment] 2020-10-19 23:44
@gerardcsaperas

First, that prompt looks like Linux, not Windows. If you're using macOS/Linux or WSL, then you want https://github.com/nvm-sh/nvm, which is for mac/Linux (and is not related to this project).

If you are actually running Windows, the problem is with `nvm install lts/dubnium`. NVM4W doesn't yet support named version downloads. You have to specify an actual version of Node, such as `14.13.0`. If you need to find a version, you can use `nvm list available` for a list.

By default, it will download 32-bit versions unless you also explicitly specify the version (i.e. `nvm install 14.13.0 64`).

**Comment by yuusakuri** [comment] 2020-11-13 20:28
- Windows10 v20H2 64bit
- WindowsPowerShell 5.x
- nvm: 1.1.7

Script1
```powershell
scoop update nvm
```
Output1
```
nvm: 1.1.7 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```
Script2
```
nvm install --lts 64
```
Output2
```
--lts.0.0
Node.js v--lts.0.0 is only available in 32-bit.
```
Script3
```
nvm install --lts 32
```
Output3
```
--lts.0.0
Version --lts.0.0 is not available. If you are attempting to download a "just released" version,
it may not be recognized by the nvm service yet (updated hourly). If you feel this is in error and
you know the version exists, please visit http://github.com/coreybutler/nodedistro and submit a PR.
```
Script4
```
nvm arch
```
Output4
```
System Default: 64-bit.
Currently Configured: -bit.
```

**Comment by coreybutler** [comment] 2020-11-15 00:17
@yuusakuri - `--lts` is not a supported flag.

**Comment by qristiam** [comment] 2021-01-04 01:29
only use your brain...

nvm install 5.4 64

just that. install nvm 6.4   64 bits... so simple

**Comment by stemtra** [comment] 2021-01-25 22:46
Hey all, I just managed to solve this by running `nvm install 14`  instead of `nvm install v14`. Second one threw the "only available in 32-bit." error, first one made the job smoothly.

Hope this helps

**Comment by naveenraina** [comment] 2021-03-07 14:19
Hi, I installed v12.21 and it worked fine. However when I tried installing another version of node with "nvm install node 14.16.0", I received the error  -
"node.0.0
Node.js vnode.0.0 is only available in 32-bit."

I changed the command to "nvm install node~14.16.0" and that worked. I have no idea why but it worked.
