### ISSUE TITLE
nvm doesn't recognize nvm install v0.10.38

### ISSUE THREAD

**Issue by wildeyes** [coreybutler/nvm-windows#56] opened 2015-04-13 11:59 UTC
The output message is confusing:
```shell
Version v0.10.38 is not available. If you are attempting to download a "just released" version,    
it may not be recognized by the nvm service yet (updated hourly). If you feel this is in error and 
you know the version exists, please visit http://github.com/coreybutler/nodedistro and submit a PR.
```
makes you think it can't connect, etc.

Maybe recognize the v in `nvm install v0.10.38`?

**Comment by coreybutler** [comment] 2015-04-13 14:14
Duplicate of issue #37.

**Closed by coreybutler** 2015-04-13 14:14 UTC
