### ISSUE TITLE
panic: runtime error: index out of range [3] with length 3

### ISSUE THREAD

**Issue by JouanDeag** [coreybutler/nvm-windows#966] opened 2023-04-15 17:05 UTC
**Issue:**

When trying to install version 19.9.0 of NodeJS through Pwsh 7.3.4 the program crashes.

**How To Reproduce:**

1. Open terminal
2. Run `nvm install 19.9.0`
3. See error

**Expected Behavior:**

I expect the version to be installed.

**Screenshots:**

![image](https://user-images.githubusercontent.com/61161558/232240597-cc80657e-6bab-416e-acf2-9941dc8667f8.png)

![image](https://user-images.githubusercontent.com/61161558/232240149-4a75418b-aa6b-4a96-8728-523267abbe14.png)

**Desktop:**
 - OS: Windows 10 22H2 19045.2846

**Additional context:**
The problem seems to be related to nvm thinking that version 19.9.0 is newer than the latest release

**Comment by coreybutler** [comment] 2023-04-15 18:14
If you're using NVM4W 1.1.10 or below, then this is another duplicate of #955. Upgrade to [v1.1.11](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11).

If you're using 1.1.11, let me know and I'll reopen the issue.

**Closed by coreybutler** 2023-04-15 18:14 UTC
Labels: duplicate
