### ISSUE TITLE
nvm use 12.4.0 error

### ISSUE THREAD

**Issue by chasangchual** [coreybutler/nvm-windows#443] opened 2019-06-07 04:01 UTC
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x ] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

success to run "nvm use 12.4.0 "

### Actual Behavior

failed with 

exit status 1: 'C:\Users\Sangchual' is not recognized as an internal or external command,
operable program or batch file.

My user account is Sangchual Cha   
Likely it failed because of the space between "Sangchual" and "Cha"

**Comment by Trifex** [comment] 2019-06-21 00:05
I don't know if you already saw this, but someone else had the same issue here.

This comment solved it for me. It's just an issue with spaces existing in the username.
https://github.com/coreybutler/nvm-windows/issues/405#issuecomment-441353018

**Comment by cnscorpions** [comment] 2019-11-04 10:53
no spaces in path, it works for me

**Comment by xmedeko** [comment] 2019-11-15 14:31
Yeah, this is duplicate of #405 and #480

**Comment by Swarag-N** [comment] 2020-05-25 06:07
### tl;dr
### Solved!!
For someone who is not able to work with ~1 method by @kirkouimet  (Thanks mate) in  #41 
Open CMD go to the Users folder and Get the Shortened Folder name.

and type 

### > `dir\x `

![Annotation 2020-05-25 112714](https://user-images.githubusercontent.com/46181010/82782765-c2d29200-9e7a-11ea-83ed-6173ddd85948.png)

Now later after copying or Noting down the folder name
![Annotation 2020-05-25 113201](https://user-images.githubusercontent.com/46181010/82783088-69b72e00-9e7b-11ea-8715-e721d7961c8c.png)

Hope it helps

**Comment by aaztha** [comment] 2020-06-22 05:09
It didn't worked for me,I didn't get any shortened version name!

**Comment by Swarag-N** [comment] 2020-06-22 05:22
The command is `dir /x` not `dir\x`

**Comment by aaztha** [comment] 2020-06-29 13:06
Yeah I wrote the same command@Swarag-N

**Comment by franciscohanna92** [comment] 2021-03-08 20:22
@aaztha Make sure to run the command from a CMD (command prompt) terminal and not a Powershell one.

**Comment by coreybutler** [comment] 2021-09-15 17:54
Spaces in paths are resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Closed by coreybutler** 2021-09-15 17:54 UTC
