### ISSUE TITLE
New installer (1.1.7) displays 1.1.5 as current version

### ISSUE THREAD

**Issue by loxy** [coreybutler/nvm-windows#375] opened 2018-08-02 14:51 UTC
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### Expected Behavior
`nvm version` should print 1.1.7. in the latest release.

### Actual Behavior
It prints 1.1.5, which was the former installed version on my system. The installer itself shows 1.1.7.
I tried to completely  uninstall the previous version, with no success.

**Comment by JonathanLoscalzo** [comment] 2018-08-02 15:13
It could be that nvm uninstall 10.X.X stills not function in this version ?

**Comment by HighvenWang** [comment] 2018-08-03 03:32
yes, I have the same problem.
and use nvm download nodejs 10.8.0,  threr is a error, it display can not install npm.

**Comment by 7sDream** [comment] 2018-08-03 08:33
Reproduce this.

**Comment by HadiAkmal** [comment] 2018-08-03 21:24
version shown as 1.1.5 instead of 1.1.7 and can't install npm

![image](https://user-images.githubusercontent.com/14165645/43666489-a9d00882-97a6-11e8-9f71-0b5fe721c122.png)

**Comment by robertmain** [comment] 2018-08-04 00:58
Yep. Same here. So I just uninstalled 1.1.6 and all my pre-compiled stuff for nothing.

**Comment by coreybutler** [comment] 2018-08-08 05:50
Duplicate of #374

**Closed by coreybutler** 2018-08-08 05:50 UTC
